'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Readable}=require('node:stream');
const {spawnSync}=require('node:child_process');
const model=require('../health/checkin-model'),store=require('../lib/health-checkin-store'),api=require('../api/health-checkins'),session=require('../lib/health-session');
function req(method,{body='',cookie='',headers={}}={}){const r=Readable.from(body?[body]:[]);r.method=method;r.headers={host:'signal.example',origin:'https://signal.example','x-forwarded-proto':'https',cookie,...headers};return r}
function res(){return{statusCode:0,headers:{},body:'',setHeader(k,v){this.headers[k.toLowerCase()]=v},end(v=''){this.body=v}}}
async function call(handler,r){const s=res();await handler(r,s);return s}
const env={...process.env};test.afterEach(()=>{process.env={...env};delete global.fetch});
test('weekly progress is accumulated sum / 7, separately from recorded average',()=>{const a=model.aggregate([{date:'2026-09-21',score:61}], '2026-09-21','week');assert.equal(a.start,'2026-09-21');assert.equal(a.end,'2026-09-27');assert.equal(a.progress,61/7);assert.equal(a.average,61);assert.equal(a.recorded,1)});
test('month uses actual calendar days and zero remains zero',()=>{assert.equal(model.aggregate([{date:'2028-02-01',score:0}],'2028-02-10','month').days,29);const a=model.aggregate([{date:'2026-04-01',score:60}],'2026-04-02','month');assert.equal(a.days,30);assert.equal(a.progress,2)});
test('consistency keeps missing sleep and alcohol unknown and measures consecutive stretches',()=>{const entries=[
  {date:'2026-09-20',schemaVersion:3,score:75,answers:{energy:8,focus:8,stress:3,calm:7,happiness:7},foundations:{sleepHours:8,alcoholCount:0}},
  {date:'2026-09-21',schemaVersion:3,score:80,answers:{energy:8,focus:8,stress:2,calm:8,happiness:8},foundations:{sleepHours:6,alcoholCount:3}},
  {date:'2026-09-22',schemaVersion:3,score:35,answers:{energy:3,focus:3,stress:8,calm:4,happiness:5},foundations:{}},
  {date:'2026-09-24',schemaVersion:3,score:30,answers:{energy:2,focus:3,stress:9,calm:3,happiness:6},foundations:{sleepHours:5}}
];const c=model.consistency(entries);assert.deepEqual(c.sleep,{answered:3,matched:2});assert.deepEqual(c.alcohol,{answered:2,matched:1});assert.equal(c.highBest,2);assert.equal(c.lowBest,1)});
test('foundation grade caps sleep, recovery, protein, and fluids while unknown is excluded',()=>{const f=model.foundations({anki:'partial',body:'recovery',sleepHours:12,proteinGrams:260,proteinTarget:130,fluidsLiters:6,fluidsTarget:3});assert.equal(f.possible,5);assert.equal(f.earned,4.5);assert.equal(f.percent,90);assert.equal(model.foundations({}).percent,null)});
test('server sanitizer retains raw metrics and recalculates subjective score',()=>{const e=store.sanitize({date:'2026-09-20',score:99,answers:{energy:0,focus:0,stress:10,calm:0,happiness:0},foundations:{anki:'no',body:'recovery',sleepHours:8,proteinTarget:130,fluidsTarget:3,foodNotes:'real note'}},'2026-09-27');assert.equal(e.score,0);assert.equal(e.foundations.body,'recovery');assert.equal(store.sanitize({...e,date:'2026-09-28'},'2026-09-27'),null)});
test('storage explicitly rejects legacy 0-5/schema-v1 entries instead of rescoring',()=>{for(const legacy of [{scaleMax:5},{schemaVersion:1}])assert.equal(store.sanitize({...legacy,date:'2026-09-20',answers:{energy:5,focus:5,stress:0,calm:5,happiness:5}},'2026-09-27'),null)});
test('API fails honestly when durable provider is absent and never returns records',async()=>{process.env.NOS_AUTH_SECRET='secret';for(const key of ['KV_REST_API_URL','KV_REST_API_TOKEN','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN','HEALTH_D1_ACCOUNT_ID','HEALTH_D1_DATABASE_ID','HEALTH_D1_API_TOKEN'])delete process.env[key];const cookie=`${session.COOKIE_NAME}=${session.createSessionValue('secret')}`;const r=await call(api,req('GET',{cookie}));assert.equal(r.statusCode,503);assert.match(r.body,/not configured/);assert.match(r.headers['cache-control'],/private, no-store/)});
test('authenticated API writes with revision and refuses silent overwrite',async()=>{process.env.NOS_AUTH_SECRET='secret';process.env.KV_REST_API_URL='https://private.invalid';process.env.KV_REST_API_TOKEN='hidden';let db=null;global.fetch=async(_url,o)=>{const cmd=JSON.parse(o.body);if(cmd[0]==='GET')return{ok:true,json:async()=>({result:db})};if(cmd[0]==='EVAL'){const expected=+cmd[4],next=cmd[5],current=db?JSON.parse(db).revision:0;if(expected!==current)return{ok:true,json:async()=>({result:0})};db=next;return{ok:true,json:async()=>({result:1})}};throw Error('unexpected')};const cookie=`${session.COOKIE_NAME}=${session.createSessionValue('secret')}`,entry={date:'2026-09-20',answers:{energy:6,focus:7,stress:3,calm:8,happiness:7},foundations:{sleepHours:8}};let r=await call(api,req('PUT',{cookie,body:JSON.stringify({revision:0,entry})}));assert.equal(r.statusCode,200);assert.equal(JSON.parse(r.body).revision,1);r=await call(api,req('PUT',{cookie,body:JSON.stringify({revision:1,entry})}));assert.equal(r.statusCode,409);assert.match(r.body,/Confirm/);r=await call(api,req('PUT',{cookie,headers:{origin:'https://evil.example'},body:'{}'}));assert.equal(r.statusCode,403)});
test('legacy import skips conflicts and keeps individual answers',async()=>{process.env.NOS_AUTH_SECRET='secret';process.env.KV_REST_API_URL='https://private.invalid';process.env.KV_REST_API_TOKEN='hidden';const original={revision:1,entries:[{date:'2026-09-20',score:50,answers:{energy:5,focus:5,stress:5,calm:5,happiness:5}}]};let db=JSON.stringify(original);global.fetch=async(_url,o)=>{const c=JSON.parse(o.body);if(c[0]==='GET')return{ok:true,json:async()=>({result:db})};db=c[5];return{ok:true,json:async()=>({result:1})}};const cookie=`${session.COOKIE_NAME}=${session.createSessionValue('secret')}`,legacy=[{date:'2026-09-20',answers:{energy:1,focus:1,stress:1,calm:1,happiness:1}},{date:'2026-09-21',answers:{energy:6,focus:6,stress:4,calm:6,happiness:6}}];const r=await call(api,req('POST',{cookie,body:JSON.stringify({revision:1,entries:legacy})}));const p=JSON.parse(r.body);assert.equal(r.statusCode,200);assert.deepEqual(p.conflicts,['2026-09-20']);assert.equal(p.entries.length,2);assert.equal(p.entries[1].answers.energy,6)});
test('D1 backend reads documents and performs one-statement revision CAS',async()=>{for(const key of ['KV_REST_API_URL','KV_REST_API_TOKEN','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN'])delete process.env[key];process.env.HEALTH_D1_ACCOUNT_ID='account';process.env.HEALTH_D1_DATABASE_ID='database';process.env.HEALTH_D1_API_TOKEN='hidden';let payload=JSON.stringify({revision:2,entries:[]}),calls=[];global.fetch=async(url,o)=>{const body=JSON.parse(o.body);calls.push({url,body,authorization:o.headers.Authorization});if(body.sql.startsWith('SELECT payload'))return{ok:true,json:async()=>({success:true,result:[{success:true,results:[{payload}]}]})};payload=body.params[2];return{ok:true,json:async()=>({success:true,result:[{success:true,meta:{changes:1}}]})}};assert.deepEqual(await store.read(),{revision:2,entries:[]});assert.equal(await store.compareAndSet(2,{revision:3,entries:[]}),true);assert.equal(calls.length,2);assert.match(calls[0].url,/\/accounts\/account\/d1\/database\/database\/query$/);assert.equal(calls[0].authorization,'Bearer hidden');assert.match(calls[1].body.sql,/ON CONFLICT\(storage_key\).*WHERE health_checkin_documents\.revision = \?/s);assert.deepEqual(calls[1].body.params.slice(-2),[2,2]);assert.equal(JSON.parse(payload).revision,3)});
test('D1 CAS SQL performs insert, second successful write, then stale conflict in real SQLite',()=>{const script=`import json,sqlite3,sys\nsql=sys.stdin.read()\ndb=sqlite3.connect(':memory:')\ndb.execute('CREATE TABLE health_checkin_documents (storage_key TEXT PRIMARY KEY, revision INTEGER NOT NULL, payload TEXT NOT NULL, updated_at TEXT NOT NULL)')\ndef cas(expected,next_revision):\n p=json.dumps({'revision':next_revision,'entries':[]})\n before=db.total_changes\n db.execute(sql,('probe',next_revision,p,'now',expected,'probe',expected,expected))\n return db.total_changes-before\nchanges=[cas(0,1),cas(1,2),cas(1,2)]\nrow=db.execute('SELECT revision,payload FROM health_checkin_documents WHERE storage_key=?',('probe',)).fetchone()\nprint(json.dumps({'changes':changes,'revision':row[0],'payloadRevision':json.loads(row[1])['revision']}))`;
  const run=spawnSync('python3',['-c',script],{input:store.D1_CAS_SQL,encoding:'utf8'});assert.equal(run.status,0,run.stderr);assert.deepEqual(JSON.parse(run.stdout),{changes:[1,1,0],revision:2,payloadRevision:2});
});
