(() => {
  'use strict';
  const GOLD = '#b59662', SIZES = { x: [1600, 900], story: [1080, 1920] };
  const $ = id => document.getElementById(id);
  const trigger = $('quote-share-trigger'), dialog = $('quote-share-dialog'), canvas = $('quote-share-canvas');
  if (!trigger || !dialog || !canvas) return;
  const ctx = canvas.getContext('2d', { alpha: false });
  const state = { format: 'x', quote: null, file: null, requestId: null, postLocked: false, postFingerprint: '', authenticated: false, generation: 0 };
  const fontsReady = document.fonts ? Promise.all([document.fonts.load('italic 80px QuoteShareCormorant'), document.fonts.load('500 24px QuoteShareInter')]).then(() => document.fonts.ready) : Promise.resolve();
  const clean = (value, type) => {
    let text = (value || '').trim();
    if (type === 'quote') text = text.replace(/^[“"']\s*/, '').replace(/\s*[”"']$/, '');
    else text = text.replace(/^\s*[—–-]\s*/, '');
    return text.trim();
  };
  function currentQuote() { return { text: clean($('qt-text')?.textContent, 'quote'), author: clean($('qt-auth')?.textContent, 'author') }; }
  function postText() { return `“${state.quote.text}”\n— ${state.quote.author}`; }
  function status(message, error = false) { const el = $('quote-share-status'); el.textContent = message; el.style.color = error ? '#d8a0a0' : ''; }
  function rule(x1, y1, x2, y2, color = GOLD, width = 1) { ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke(); }
  function wrap(text, width) { const words=text.split(/\s+/), lines=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(!line||ctx.measureText(next).width<=width)line=next;else{lines.push(line);line=word;}}if(line)lines.push(line);return lines; }
  function fit(text, width, height, max, min) { for(let size=max;size>=min;size-=2){ctx.font=`italic 400 ${size}px QuoteShareCormorant, Georgia, serif`;const lines=wrap(text,width);if(lines.length*size*1.2<=height)return{size,lines,lineHeight:size*1.2};}ctx.font=`italic 400 ${min}px QuoteShareCormorant, Georgia, serif`;return{size:min,lines:wrap(text,width),lineHeight:min*1.2}; }
  function drawBolt(w,h) { const image=$('quote-share-bolt-source');const bw=h>w?74:58,bh=bw*1.32;ctx.drawImage(image,w-(h>w?104:115),h>w?105:68,bw,bh); }
  function render() {
    const [w,h]=SIZES[state.format], story=h>w;canvas.width=w;canvas.height=h;
    ctx.fillStyle='#070707';ctx.fillRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.42,h*.38,20,w*.42,h*.38,Math.max(w,h)*.72);glow.addColorStop(0,'#19150e');glow.addColorStop(1,'#070707');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);drawBolt(w,h);
    const left=story?126:190, right=story?100:150;ctx.textBaseline='top';ctx.textAlign='left';ctx.fillStyle='#e6e2d9';ctx.font=`500 ${story?27:23}px QuoteShareInter, sans-serif`;ctx.fillText(state.quote.author,left,story?245:135);
    const quoteTop=story?600:300, quoteHeight=story?700:350, fitted=fit(state.quote.text,w-left-right,quoteHeight,story?94:82,story?54:44);rule(left-42,quoteTop-18,left-42,quoteTop+Math.max(quoteHeight*.78,fitted.lines.length*fitted.lineHeight),GOLD,2);
    let y=quoteTop;fitted.lines.forEach((line,i)=>{ctx.fillStyle=i===fitted.lines.length-1?GOLD:'#f0eee8';ctx.fillText(line,left,y);y+=fitted.lineHeight;});rule(left,story?h-280:h-140,w-right,story?h-280:h-140,'rgba(181,150,98,.25)',1);
    document.querySelectorAll('[data-quote-format]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.quoteFormat===state.format)));
  }
  const blob = () => new Promise(resolve => canvas.toBlob(resolve,'image/png'));
  function filename(){return `quote-margin-${state.format==='x'?'1600x900':'1080x1920'}.png`;}
  async function prepareFile(){const generation=++state.generation,snapshot={format:state.format,quote:{...state.quote}};state.file=null;$('quote-share-native').disabled=true;$('quote-share-download').disabled=true;await Promise.all([fontsReady,$('quote-share-bolt-source').decode?.().catch(()=>{})]);if(generation!==state.generation)return;state.format=snapshot.format;state.quote=snapshot.quote;render();const b=await blob();if(generation!==state.generation)return;state.file=new File([b],filename(),{type:'image/png'});$('quote-share-native').disabled=false;$('quote-share-download').disabled=false;status('Image ready.');}
  async function open(){const quote=currentQuote(),fingerprint=`${quote.text}\n${quote.author}\n${state.format}`;if(fingerprint!==state.postFingerprint){state.requestId=null;state.postLocked=false;state.postFingerprint=fingerprint;}state.quote=quote;state.file=null;$('quote-post-final').hidden=true;$('quote-post-confirm').disabled=true;document.querySelectorAll('[data-quote-format]').forEach(b=>b.disabled=state.postLocked);status('Preparing image…');dialog.showModal();await prepareFile();}
  async function download(){if(!state.file)await prepareFile();const url=URL.createObjectURL(state.file),a=document.createElement('a');a.href=url;a.download=filename();a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);status(`PNG ready: ${filename()}`);}
  async function nativeShare(){if(!state.file)return status('Image is still preparing. Use Download PNG if sharing remains unavailable.',true);if(!navigator.share||!navigator.canShare?.({files:[state.file]}))return status('Native file sharing is unavailable. Download the PNG instead.',true);try{await navigator.share({files:[state.file]});status('Share sheet opened.');}catch(e){if(e.name!=='AbortError')status('The share sheet could not be opened. Download the PNG instead.',true);}}
  async function copy(){try{await navigator.clipboard.writeText(postText());status('Quote and author copied — nothing else appended.');}catch{status('Clipboard permission was denied.',true);}}
  function setPostStatus(message,url=''){const box=$('quote-post-status');box.replaceChildren(document.createTextNode(message));if(url){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=' View verified post on X.';a.style.color=GOLD;box.append(a);}}
  async function review(){if(state.postLocked)return setPostStatus('Posting is locked for this exact image to prevent a duplicate.');state.requestId ||= crypto.randomUUID();$('quote-post-final').hidden=false;$('quote-post-auth').hidden=true;$('quote-post-confirm').disabled=true;setPostStatus('Checking posting access…');try{const r=await fetch('/api/quote-post',{credentials:'same-origin'}),info=await r.json();if(!r.ok||info.configured===false||info.account!=='Novairecito'){if(r.status===401)$('quote-post-auth').hidden=false;return setPostStatus(r.status===401?'Authenticate to enable explicit posting confirmation.':'Posting backend is not configured for @Novairecito.');}if(info.authenticated!==true){$('quote-post-auth').hidden=false;return setPostStatus('Authenticate to enable explicit posting confirmation.');}state.authenticated=true;$('quote-post-confirm').disabled=false;setPostStatus('Authenticated. Explicit confirmation is still required.');}catch{setPostStatus('Posting status unavailable. Export and copy still work.');}}
  async function authenticate(){const pin=$('quote-post-pin').value;if(!pin)return setPostStatus('Enter the portfolio PIN.');$('quote-post-auth-button').disabled=true;try{const r=await fetch('/api/quote-auth',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});$('quote-post-pin').value='';if(!r.ok)return setPostStatus('Authentication failed.');state.authenticated=true;$('quote-post-auth').hidden=true;$('quote-post-confirm').disabled=false;setPostStatus('Authenticated. Review once more, then explicitly confirm.');}catch{setPostStatus('Authentication service is unavailable.');}finally{$('quote-post-auth-button').disabled=false;}}
  async function confirmPost(){if(state.postLocked)return;if(!state.file)return setPostStatus('Wait for the image to finish preparing.');const text=postText();if([...text].length>280)return setPostStatus('Blocked: post text exceeds 280 characters.');if(!state.authenticated)return setPostStatus('Authenticate before confirming.');const button=$('quote-post-confirm'),formatButtons=[...document.querySelectorAll('[data-quote-format]')];button.disabled=true;formatButtons.forEach(b=>b.disabled=true);state.postLocked=true;try{const imageDataUrl=canvas.toDataURL('image/png');const r=await fetch('/api/quote-post',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,imageDataUrl,confirmation:true,requestId:state.requestId})}),result=await r.json().catch(()=>({}));if(r.status===401){state.authenticated=false;state.postLocked=false;formatButtons.forEach(b=>b.disabled=false);$('quote-post-auth').hidden=false;setPostStatus('Session expired before posting. Authenticate again, then explicitly confirm. Nothing was retried automatically.');return;}if(!r.ok){setPostStatus(result.error||`Posting was rejected (${r.status}). This exact request is locked to prevent a duplicate.`);return;}if(result.ok!==true||!result.url)throw new Error('unverified response');setPostStatus('Post verified.',result.url);}catch{setPostStatus('Could not confirm posting. Check @Novairecito before retrying. This request is locked to prevent a duplicate.');}finally{button.disabled=true;}}
  trigger.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open();});trigger.addEventListener('pointerdown',e=>e.stopPropagation());
  $('quote-share-close').addEventListener('click',()=>dialog.close());$('quote-share-native').addEventListener('click',nativeShare);$('quote-share-download').addEventListener('click',download);$('quote-share-copy').addEventListener('click',copy);$('quote-post-review').addEventListener('click',review);$('quote-post-auth-button').addEventListener('click',authenticate);$('quote-post-confirm').addEventListener('click',confirmPost);
  document.querySelectorAll('[data-quote-format]').forEach(button=>button.addEventListener('click',async()=>{if(state.postLocked)return;state.format=button.dataset.quoteFormat;state.postFingerprint=`${state.quote.text}\n${state.quote.author}\n${state.format}`;state.requestId=null;state.file=null;status('Preparing image…');await prepareFile();}));
  dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
})();
