(() => {
  'use strict';
  const GOLD = '#b59662', SIZES = { x: [1600, 900], story: [1080, 1920] };
  const $ = id => document.getElementById(id);
  const triggers = [...document.querySelectorAll('[data-share-kind]')], dialog = $('quote-share-dialog'), canvas = $('quote-share-canvas');
  if (!triggers.length || !dialog || !canvas) return;
  const ctx = canvas.getContext('2d', { alpha: false });
  const state = { format: 'x', item: null, file: null, authenticated: false, generation: 0, attempts: new Map() };
  const fontsReady = document.fonts ? Promise.all([document.fonts.load('italic 80px QuoteShareCormorant'), document.fonts.load('500 24px QuoteShareInter')]).then(() => document.fonts.ready) : Promise.resolve();
  const cleanQuote = value => (value || '').trim().replace(/^[“"']\s*/, '').replace(/\s*[”"']$/, '').trim();
  const cleanAuthor = value => (value || '').trim().replace(/^\s*[—–-]\s*/, '').trim();
  const VERIFIED_SOURCES = new Map([
    ['Carl Jung\nUntil you make the unconscious conscious, it will direct your life and you will call it fate.', 'Paraphrase · Aion, §126']
  ]);
  function snapshot(kind) {
    if (kind === 'meditation') return { kind, title: $('med-title')?.textContent.trim() || 'Daily meditation', text: $('med-excerpt')?.textContent.trim() || '', author: 'Novairecito', source: $('med-excerpt')?.dataset.shareSource || '' };
    const text=cleanQuote($('qt-text')?.textContent),author=cleanAuthor($('qt-auth')?.textContent);
    return { kind, title: '', text, author, source: $('qt-auth')?.dataset.shareSource || VERIFIED_SOURCES.get(`${author}\n${text}`) || '' };
  }
  function copyText() { const i=state.item; return i.kind==='meditation' ? `${i.title}\n\n${i.text}\n— Novairecito` : `“${i.text}”\n— ${i.author}`; }
  function fingerprint(item=state.item,format=state.format){return [item.kind,item.title,item.text,item.author,item.source,format].join('\n');}
  function attempt(){const key=fingerprint();if(!state.attempts.has(key))state.attempts.set(key,{requestId:crypto.randomUUID(),status:'idle'});return state.attempts.get(key);}
  function status(message, error=false){const el=$('quote-share-status');el.textContent=message;el.style.color=error?'#d8a0a0':'';}
  function postStatus(message,url=''){const box=$('quote-post-status');box.replaceChildren(document.createTextNode(message));if(url){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=' View verified post on X.';a.style.color=GOLD;box.append(a);}}
  function rule(x1,y1,x2,y2,color=GOLD,width=1){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
  function wrap(text,width){const paragraphs=text.split(/\n+/), lines=[];for(const paragraph of paragraphs){const words=paragraph.split(/\s+/).filter(Boolean);let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(!line||ctx.measureText(next).width<=width)line=next;else{lines.push(line);line=word;}}if(line)lines.push(line);if(paragraph!==paragraphs.at(-1))lines.push('');}return lines;}
  function fit(text,width,height,max,min=18){for(let size=max;size>=min;size-=2){ctx.font=`italic 400 ${size}px QuoteShareCormorant, Georgia, serif`;const lines=wrap(text,width),lineHeight=size*1.18;if(lines.length*lineHeight<=height)return{size,lines,lineHeight};}ctx.font=`italic 400 ${min}px QuoteShareCormorant, Georgia, serif`;return{size:min,lines:wrap(text,width),lineHeight:min*1.18};}
  function drawBolt(w,h){const image=$('quote-share-bolt-source'),bw=h>w?74:58,bh=bw*1.32;ctx.drawImage(image,w-(h>w?104:115),h-bh-(h>w?105:68),bw,bh);}
  function render(){
    const [w,h]=SIZES[state.format],story=h>w,i=state.item;canvas.width=w;canvas.height=h;
    ctx.fillStyle='#070707';ctx.fillRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.42,h*.38,20,w*.42,h*.38,Math.max(w,h)*.72);glow.addColorStop(0,'#19150e');glow.addColorStop(1,'#070707');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);drawBolt(w,h);
    const left=story?126:190,right=story?100:150,top=story?390:190,bottom=story?390:190,authorSpace=story?150:100;
    const imageText=i.kind==='meditation'?`${i.title}\n\n${i.text}`:i.text;
    const fitted=fit(imageText,w-left-right,h-top-bottom-authorSpace,i.kind==='meditation'?(story?76:66):(story?94:82),i.kind==='meditation'?18:(story?44:36));
    rule(left-42,top-18,left-42,top+fitted.lines.length*fitted.lineHeight,GOLD,2);ctx.textBaseline='top';ctx.textAlign='left';let y=top;
    fitted.lines.forEach((line,index)=>{ctx.fillStyle=index===fitted.lines.length-1?GOLD:'#f0eee8';ctx.fillText(line,left,y);y+=fitted.lineHeight;});
    ctx.fillStyle='#e6e2d9';ctx.font=`500 ${story?27:23}px QuoteShareInter, sans-serif`;ctx.fillText(i.author,left,y+(story?54:32));
    if(i.source){ctx.fillStyle='#8f8995';ctx.font=`500 ${story?21:18}px QuoteShareInter, sans-serif`;ctx.fillText(i.source,left,y+(story?98:68));}
    rule(left,story?h-280:h-140,w-right,story?h-280:h-140,'rgba(181,150,98,.25)',1);
    document.querySelectorAll('[data-quote-format]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.quoteFormat===state.format)));
  }
  const blob=()=>new Promise(resolve=>canvas.toBlob(resolve,'image/png'));
  function filename(){return `${state.item.kind}-margin-${state.format==='x'?'1600x900':'1080x1920'}.png`;}
  async function prepareFile(){const generation=++state.generation,snapshotItem={...state.item},snapshotFormat=state.format;state.file=null;$('quote-share-native').disabled=true;$('quote-share-download').disabled=true;$('quote-post-confirm').disabled=true;await Promise.all([fontsReady,$('quote-share-bolt-source').decode?.().catch(()=>{})]);if(generation!==state.generation)return;state.item=snapshotItem;state.format=snapshotFormat;render();const b=await blob();if(generation!==state.generation)return;state.file=new File([b],filename(),{type:'image/png'});$('quote-share-native').disabled=false;$('quote-share-download').disabled=false;const a=attempt();$('quote-post-confirm').disabled=!state.authenticated||a.status!=='idle';status('Image ready.');if(a.status!=='idle')postStatus('This exact image is locked to prevent a duplicate.');}
  async function checkAccess(){postStatus('Checking posting access…');try{const r=await fetch('/api/quote-post',{credentials:'same-origin'}),info=await r.json();if(r.ok&&info.configured!==false&&info.account==='Novairecito'&&info.authenticated===true){state.authenticated=true;$('quote-post-auth').hidden=true;$('quote-post-confirm').disabled=!state.file||attempt().status!=='idle';return postStatus(attempt().status==='idle'?'Ready. Yes posts this image only.':'This exact image is locked to prevent a duplicate.');}state.authenticated=false;$('quote-post-auth').hidden=false;postStatus((r.status===401||(r.ok&&info.configured!==false&&info.account==='Novairecito'))?'Enter the NOS PIN, then press Yes.':'Posting backend is not configured for @Novairecito.');}catch{state.authenticated=false;$('quote-post-auth').hidden=false;postStatus('Posting status unavailable. Downloads still work.');}}
  async function open(kind){state.item=snapshot(kind);state.format='x';state.file=null;state.authenticated=false;$('quote-post-auth').hidden=true;$('quote-post-confirm').disabled=true;document.querySelectorAll('[data-quote-format]').forEach(b=>b.disabled=false);$('quote-post-preview').textContent='Image only · @Novairecito';postStatus('');status('Preparing image…');dialog.showModal();await Promise.all([prepareFile(),checkAccess()]);}
  async function download(){if(!state.file)await prepareFile();const url=URL.createObjectURL(state.file),a=document.createElement('a');a.href=url;a.download=filename();a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);status(`PNG ready: ${filename()}`);}
  async function nativeShare(){if(!state.file)return status('Image is still preparing.',true);if(!navigator.share||!navigator.canShare?.({files:[state.file]}))return status('Native file sharing is unavailable. Download the PNG instead.',true);try{await navigator.share({files:[state.file]});status('Share sheet opened.');}catch(e){if(e.name!=='AbortError')status('The share sheet could not be opened.',true);}}
  async function copy(){try{await navigator.clipboard.writeText(copyText());status('Text copied — nothing else appended.');}catch{status('Clipboard permission was denied.',true);}}
  async function authenticate(){const pin=$('quote-post-pin').value;if(!pin)return postStatus('Enter the NOS PIN.');$('quote-post-auth-button').disabled=true;try{const r=await fetch('/api/quote-auth',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});$('quote-post-pin').value='';if(!r.ok)return postStatus('Authentication failed.');state.authenticated=true;$('quote-post-auth').hidden=true;const a=attempt();$('quote-post-confirm').disabled=!state.file||a.status!=='idle';postStatus(a.status==='idle'?'Authenticated. Press Yes to post this image only.':'This exact image is locked to prevent a duplicate.');}catch{postStatus('Authentication service is unavailable.');}finally{$('quote-post-auth-button').disabled=false;}}
  async function confirmPost(){const entry=attempt();if(entry.status!=='idle'||!state.file)return;if(!state.authenticated)return postStatus('Enter the NOS PIN before pressing Yes.');const key=fingerprint(),button=$('quote-post-confirm'),formats=[...document.querySelectorAll('[data-quote-format]')],payload={text:'',imageDataUrl:canvas.toDataURL('image/png'),confirmation:true,requestId:entry.requestId};button.disabled=true;formats.forEach(b=>b.disabled=true);entry.status='pending';try{const r=await fetch('/api/quote-post',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await r.json().catch(()=>({}));if(r.status===401){entry.status='idle';if(fingerprint()===key){state.authenticated=false;formats.forEach(b=>b.disabled=false);$('quote-post-auth').hidden=false;postStatus('Session expired. Authenticate again; nothing was retried.');}return;}entry.status='locked';if(fingerprint()!==key)return;if(!r.ok)return postStatus(result.error||`Posting was rejected (${r.status}). This exact image is locked to prevent a duplicate.`);if(result.ok!==true||!result.url)throw new Error('unverified response');entry.status='success';postStatus('Post verified.',result.url);}catch{entry.status='locked';if(fingerprint()===key)postStatus('Could not confirm posting. Check @Novairecito before retrying. This exact image is locked.');}finally{if(fingerprint()===key)formats.forEach(b=>b.disabled=false);}}
  triggers.forEach(trigger=>{trigger.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(trigger.dataset.shareKind);});trigger.addEventListener('pointerdown',e=>e.stopPropagation());});
  $('quote-share-close').addEventListener('click',()=>dialog.close());$('quote-share-native').addEventListener('click',nativeShare);$('quote-share-download').addEventListener('click',download);$('quote-share-copy').addEventListener('click',copy);$('quote-post-auth-button').addEventListener('click',authenticate);$('quote-post-confirm').addEventListener('click',confirmPost);
  document.querySelectorAll('[data-quote-format]').forEach(button=>button.addEventListener('click',async()=>{state.format=button.dataset.quoteFormat;await prepareFile();}));
  dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
})();
