const { chromium } = require('/tmp/quote-studio-qa/node_modules/playwright');
const assert = require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:8767/',{waitUntil:'domcontentloaded'});
const corpus=await page.evaluate(()=>eval('[...QUOTES_INVESTING,...QUOTES_PSYCHOLOGY]'));assert.ok(corpus.length>=60);
for(const q of corpus){await page.evaluate(q=>{document.querySelector('#qt-text').textContent='“'+q.text+'”';document.querySelector('#qt-auth').textContent='— '+q.author;},q);await page.click('#quote-share-trigger');await page.waitForFunction(()=>document.querySelector('#quote-share-status').textContent.toLowerCase().includes('ready'));const dims=await page.evaluate(()=>{const c=document.querySelector('#quote-share-canvas'),d=document.querySelector('#quote-share-dialog');return[c.width,c.height,d.scrollWidth<=innerWidth];});assert.deepEqual(dims,[1600,900,true]);await page.keyboard.press('Escape');}
const first=corpus[0],next=corpus[1];await page.evaluate(q=>{document.querySelector('#qt-text').textContent='“'+q.text+'”';document.querySelector('#qt-auth').textContent='— '+q.author;},first);await page.click('#quote-share-trigger');await page.waitForFunction(()=>document.querySelector('#quote-share-status').textContent.toLowerCase().includes('ready'));await page.click('#quote-share-copy');assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),`“${first.text}”\n— ${first.author}`);await page.keyboard.press('Escape');await page.evaluate(q=>{document.querySelector('#qt-text').textContent='“'+q.text+'”';document.querySelector('#qt-auth').textContent='— '+q.author;},next);await page.click('#quote-share-trigger');await page.waitForFunction(()=>document.querySelector('#quote-share-status').textContent.toLowerCase().includes('ready'));await page.click('[data-quote-format="story"]');await page.waitForFunction(()=>document.querySelector('#quote-share-status').textContent.toLowerCase().includes('ready'));assert.deepEqual(await page.evaluate(()=>[document.querySelector('#quote-share-canvas').width,document.querySelector('#quote-share-canvas').height]),[1080,1920]);const dl=page.waitForEvent('download');await page.click('#quote-share-download');assert.equal((await dl).suggestedFilename(),'quote-margin-1080x1920.png');await page.keyboard.press('Escape');assert.equal(await page.locator('#quote-share-dialog').evaluate(d=>d.open),false);
// MOCKED BACKEND ONLY: verifies confirmation contract; no network or real post.
await page.route('**/api/quote-post',async route=>{if(route.request().method()==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configured:true,account:'Novairecito',authenticated:true})});const body=route.request().postDataJSON();assert.equal(body.confirmation,true);assert.equal(body.text,`“${next.text}”\n— ${next.author}`);assert.match(body.imageDataUrl,/^data:image\/png;base64,/);return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,url:'https://x.invalid/mock'})});});await page.click('#quote-share-trigger');await page.waitForFunction(()=>document.querySelector('#quote-share-status').textContent.toLowerCase().includes('ready'));await page.click('#quote-post-review');await page.waitForFunction(()=>!document.querySelector('#quote-post-confirm').disabled);await page.click('#quote-post-confirm');await page.waitForFunction(()=>document.querySelector('#quote-post-status').textContent.includes('Post verified.'));
const font=await page.evaluate(()=>document.fonts.check('italic 80px QuoteShareCormorant'));assert.equal(font,true);assert.deepEqual(errors,[]);console.log(`integrated quote share QA: ok (${corpus.length} main quote entries, dynamic copy/export, mobile, Escape, local font, mocked confirmed post)`);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
