import * as THREE from './vendor/three.module.min.js';
import { OrbitControls } from './vendor/OrbitControls.js';
import { OBJLoader } from './vendor/OBJLoader.js';

const MUSCLES={
 pectoralis:{name:'Pectoralis major',region:'Torso',group:'torso',view:'Anterior',info:'A broad chest muscle that adducts and internally rotates the upper arm.',files:['FJ1446','FJ1446M','FJ1447','FJ1447M','FJ1464','FJ1464M']},
 oblique:{name:'External oblique',region:'Torso',group:'torso',view:'Anterior / lateral',info:'A superficial abdominal muscle involved in trunk rotation, side-bending and compression.',files:['FJ1452','FJ1452M']},
 serratus:{name:'Serratus anterior',region:'Torso',group:'torso',view:'Lateral',info:'Runs from the upper ribs to the shoulder blade, helping protract and stabilize the scapula.',files:['FJ1459','FJ1459M']},
 deltoid:{name:'Deltoid',region:'Shoulder',group:'upper',view:'All views',info:'The rounded shoulder muscle; its fibers raise the arm and assist front-to-back movement.',files:['FJ1467','FJ1467M','FJ1468','FJ1468M','FJ1513','FJ1513M']},
 biceps:{name:'Biceps brachii',region:'Upper arm',group:'upper',view:'Anterior',info:'A two-headed upper-arm muscle that flexes the elbow and supinates the forearm.',files:['FJ1478','FJ1478M','FJ1512','FJ1512M']},
 triceps:{name:'Triceps brachii',region:'Upper arm',group:'upper',view:'Posterior',info:'The large posterior upper-arm muscle and primary extensor of the elbow.',files:['FJ1477','FJ1477M','FJ1479','FJ1479M']},
 trapezius:{name:'Trapezius',region:'Upper back',group:'torso',view:'Posterior',info:'A broad superficial muscle that moves and stabilizes the shoulder blades and supports the neck.',files:['FJ1520','FJ1520M','FJ1521','FJ1521M','FJ1554','FJ1554M']},
 gluteus:{name:'Gluteus maximus',region:'Hip',group:'lower',view:'Posterior',info:'The largest gluteal muscle, powering hip extension and outward rotation.',files:['FJ1418','FJ1418M']},
 quadriceps:{name:'Quadriceps femoris',region:'Thigh',group:'lower',view:'Anterior',info:'Front-thigh muscles that extend the knee.',files:['FJ1433','FJ1433M','FJ1442','FJ1442M']},
 adductor:{name:'Adductor longus',region:'Thigh',group:'lower',view:'Anterior / medial',info:'A medial thigh muscle that draws the thigh toward the body midline.',files:['FJ1402','FJ1402M']},
 hamstrings:{name:'Biceps femoris',region:'Thigh',group:'lower',view:'Posterior',info:'A posterior thigh muscle that flexes the knee and extends the hip.',files:['FJ1395','FJ1395M']},
 tibialis:{name:'Tibialis anterior',region:'Lower leg',group:'lower',view:'Anterior',info:'Runs along the shin and dorsiflexes the ankle, lifting the foot upward.',files:['FJ1439','FJ1439M']},
 gastrocnemius:{name:'Gastrocnemius',region:'Calf',group:'lower',view:'Posterior',info:'The prominent two-headed calf muscle that plantarflexes the ankle and assists knee flexion.',files:['FJ1394','FJ1394M','FJ1397','FJ1397M']},
 soleus:{name:'Soleus',region:'Calf',group:'lower',view:'Posterior / lateral',info:'A deep calf muscle important for standing posture and plantarflexing the foot.',files:['FJ1437','FJ1437M']}
};
const order=Object.keys(MUSCLES),canvas=document.querySelector('#atlas-canvas'),viewport=document.querySelector('#viewport');
let scene,camera,renderer,controls,body,selected=null,hovered=null,parts=[],autoRotate=false,viewTween=0,pointerStart=null;
const loader=new OBJLoader(), modelScale=.00605, modelCenterZ=801;
function muscleMaterial(){const m=new THREE.MeshPhysicalMaterial({color:0xe8e3d7,roughness:.56,metalness:.04,clearcoat:.22,emissive:0x082226,emissiveIntensity:.34});m.onBeforeCompile=s=>{s.fragmentShader=s.fragmentShader.replace('#include <emissivemap_fragment>',`#include <emissivemap_fragment>\nfloat fiber=pow(abs(sin(vViewPosition.y*17.0+vViewPosition.x*7.0)),18.0); totalEmissiveRadiance += vec3(0.08,0.38,0.42)*fiber;`)};return m}
function prepObject(obj,key,material){obj.rotation.x=-Math.PI/2;obj.scale.setScalar(modelScale);obj.position.y=-modelCenterZ*modelScale;obj.traverse(c=>{if(!c.isMesh)return;c.geometry.computeVertexNormals();c.material=material.clone();c.userData.key=key;parts.push(c)});body.add(obj)}
async function loadObj(file){return loader.loadAsync(`./models/${file}.obj`)}
async function buildBody(){body=new THREE.Group();scene.add(body);const shell=await loadObj('FJ2810');shell.rotation.x=-Math.PI/2;shell.scale.setScalar(modelScale);shell.position.y=-modelCenterZ*modelScale;shell.traverse(c=>{if(c.isMesh){c.geometry.computeVertexNormals();c.material=new THREE.MeshPhysicalMaterial({color:0xdaf8f8,transparent:true,opacity:.105,roughness:.25,metalness:.12,depthWrite:false,side:THREE.DoubleSide,emissive:0x0e5f68,emissiveIntensity:.52})}});body.add(shell);
 const jobs=[];for(const [key,m] of Object.entries(MUSCLES))for(const f of m.files)jobs.push(loadObj(f).then(o=>prepObject(o,key,muscleMaterial())));await Promise.all(jobs);
}
async function init(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.34;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(28,1,.1,100);camera.position.set(0,.1,22);controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=8;controls.maxDistance=32;controls.target.set(0,0,0);controls.autoRotate=false;controls.autoRotateSpeed=.35;controls.enablePan=false;controls.saveState();controls.addEventListener('start',()=>{autoRotate=false;controls.autoRotate=false});scene.add(new THREE.HemisphereLight(0xeaffff,0x050608,2.8));const key=new THREE.DirectionalLight(0xffffff,5.5);key.position.set(-4,8,7);scene.add(key);const rim=new THREE.DirectionalLight(0x42eaff,4);rim.position.set(5,1,-7);scene.add(rim);await buildBody();resize();addEvents();animate();window.__HEALTH_ATLAS__={ready:true,muscleCount:order.length,get selected(){return selected},get state(){return {camera:camera.position.toArray(),target:controls.target.toArray(),autoRotate,controlsAutoRotate:controls.autoRotate}},view:setView,parts:parts.length,project:key=>projectMuscle(key),projectAll:key=>projectMuscles(key)};document.documentElement.dataset.atlasReady='true'}catch(e){console.error(e);document.querySelector('#webgl-fallback').hidden=false;document.querySelector('#search').addEventListener('input',filterList);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filterList()});window.__HEALTH_ATLAS__={ready:false,error:String(e)}}}
function resize(){if(!renderer)return;const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function hit(clientX,clientY){if(!camera||!parts.length)return null;const r=canvas.getBoundingClientRect(),mouse=new THREE.Vector2((clientX-r.left)/r.width*2-1,-(clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);return ray.intersectObjects(parts,false)[0]?.object||null}
function projectMuscle(key){return projectMuscles(key)[0]||null}
function projectMuscles(key){const r=canvas.getBoundingClientRect();return parts.filter(p=>p.userData.key===key).map(target=>{const p=new THREE.Box3().setFromObject(target).getCenter(new THREE.Vector3()).project(camera);return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}})}
function addEvents(){window.addEventListener('resize',resize);canvas.addEventListener('pointermove',e=>{if(e.buttons)return;hovered=hit(e.clientX,e.clientY);canvas.style.cursor=hovered?'crosshair':'grab';const t=document.querySelector('#tooltip');if(hovered){t.style.display='block';t.style.left=e.offsetX+'px';t.style.top=e.offsetY+'px';t.textContent=MUSCLES[hovered.userData.key].name.toUpperCase()}else t.style.display='none'});canvas.addEventListener('pointerdown',e=>pointerStart={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(pointerStart&&Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)<8){const m=hit(e.clientX,e.clientY);if(m)selectMuscle(m.userData.key)}pointerStart=null});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelector('#zoom-in').onclick=()=>zoom(-1.8);document.querySelector('#zoom-out').onclick=()=>zoom(1.8);document.querySelector('#focus-button').onclick=()=>selected&&focusSelected();document.querySelector('#close-inspector').onclick=clearSelection;document.querySelector('#search').addEventListener('input',filterList);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filterList()})}
function setView(view){document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));autoRotate=false;controls.autoRotate=false;cancelAnimationFrame(viewTween);controls.enableDamping=false;controls.reset();if(view==='reset'){clearSelection();camera.position.set(0,.1,22);controls.target.set(0,0,0);controls.update();controls.enableDamping=true;return}const distance=THREE.MathUtils.clamp(camera.position.distanceTo(controls.target),controls.minDistance,controls.maxDistance);controls.target.set(0,0,0);camera.position.set(0,.1,view==='back'?-distance:distance);controls.update();controls.enableDamping=true}
function tweenCamera(destination,target){const p0=camera.position.clone(),t0=controls.target.clone(),start=performance.now();(function step(now){const p=Math.min(1,(now-start)/520),q=1-Math.pow(1-p,3);camera.position.lerpVectors(p0,destination,q);controls.target.lerpVectors(t0,target,q);controls.update();if(p<1)viewTween=requestAnimationFrame(step)})(start)}
function zoom(delta){const direction=camera.position.clone().sub(controls.target).normalize(),distance=THREE.MathUtils.clamp(camera.position.distanceTo(controls.target)+delta,controls.minDistance,controls.maxDistance);camera.position.copy(controls.target).addScaledVector(direction,distance);controls.update()}
function selectMuscle(key){if(!MUSCLES[key])return;selected=key;autoRotate=false;controls.autoRotate=false;const m=MUSCLES[key],i=order.indexOf(key)+1;document.querySelector('#muscle-number').textContent=String(i).padStart(2,'0');document.querySelector('#muscle-name').textContent=m.name;document.querySelector('#muscle-meta').textContent=m.info;document.querySelector('#muscle-region').textContent=m.region.toUpperCase();document.querySelector('#muscle-view').textContent=m.view.toUpperCase();document.querySelector('#focus-button').disabled=false;document.querySelectorAll('.muscle-item').forEach(el=>el.classList.toggle('selected',el.dataset.key===key));window.dispatchEvent(new CustomEvent('atlas:select',{detail:{key,name:m.name}}))}
function clearSelection(){selected=null;document.querySelector('#muscle-number').textContent='00';document.querySelector('#muscle-name').textContent='Select a muscle';document.querySelector('#muscle-meta').textContent='Touch an illuminated muscle to begin.';document.querySelector('#muscle-region').textContent='—';document.querySelector('#muscle-view').textContent='—';document.querySelector('#focus-button').disabled=true;document.querySelectorAll('.muscle-item').forEach(el=>el.classList.remove('selected'))}
function focusSelected(){const targets=parts.filter(p=>p.userData.key===selected);if(!targets.length)return;const box=new THREE.Box3();targets.forEach(p=>box.expandByObject(p));const c=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length(),dir=camera.position.clone().sub(controls.target).normalize();tweenCamera(c.clone().addScaledVector(dir,Math.max(controls.minDistance,size*3.2)),c)}
function animate(){requestAnimationFrame(animate);if(autoRotate)body.rotation.y+=.0017;for(const p of parts){const on=p.userData.key===selected,over=p===hovered;p.material.color.setHex(on?0xbdfaff:over?0xffffff:0xe8e3d7);p.material.emissive.setHex(on?0x22cfe5:over?0x17616b:0x082226);p.material.emissiveIntensity=on?1.65:over?.9:.34}controls.update();renderer.render(scene,camera)}
function renderList(){const list=document.querySelector('#muscle-list');list.innerHTML=order.map((k,i)=>{const m=MUSCLES[k];return `<button class="muscle-item" data-key="${k}" data-group="${m.group}" data-search="${(m.name+' '+m.region).toLowerCase()}"><span class="idx">${String(i+1).padStart(2,'0')}</span><span><b>${m.name}</b><small>${m.region.toUpperCase()} · ${m.view.toUpperCase()}</small></span><span class="arrow">↗</span></button>`}).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectMuscle(b.dataset.key);viewport.scrollIntoView({behavior:'smooth',block:'center'})})}
function filterList(){const q=document.querySelector('#search').value.toLowerCase().trim(),g=document.querySelector('[data-filter].active')?.dataset.filter||'all';document.querySelectorAll('.muscle-item').forEach(el=>el.hidden=!(el.dataset.search.includes(q)&&(g==='all'||el.dataset.group===g)))}
renderList();init();