import * as THREE from './vendor/three.module.min.js';
import { OrbitControls } from './vendor/OrbitControls.js';
import { GLTFLoader } from './vendor/GLTFLoader.js';
import { MeshoptDecoder } from './vendor/meshopt_decoder.module.js';

const MUSCLES={
 pectoralis:{name:'Pectoralis major',region:'Torso',group:'torso',view:'Anterior',info:'A broad chest muscle that adducts and internally rotates the upper arm.',files:['FJ1446','FJ1446M','FJ1447','FJ1447M','FJ1464','FJ1464M']},
 oblique:{name:'External oblique',region:'Torso',group:'torso',view:'Anterior / lateral',info:'A superficial abdominal muscle involved in trunk rotation, side-bending and compression.',files:['FJ1452','FJ1452M']},
 serratus:{name:'Serratus anterior',region:'Torso',group:'torso',view:'Lateral',info:'Runs from the upper ribs to the shoulder blade, helping protract and stabilize the scapula.',files:['FJ1459','FJ1459M']},
 deltoid:{name:'Deltoid',region:'Shoulder',group:'upper',view:'All views',info:'The rounded shoulder muscle; its fibers raise the arm and assist front-to-back movement.',files:['FJ1467','FJ1467M','FJ1468','FJ1468M','FJ1513','FJ1513M']},
 biceps:{name:'Biceps brachii',region:'Upper arm',group:'upper',view:'Anterior',info:'A two-headed upper-arm muscle that flexes the elbow and supinates the forearm.',files:['FJ1478','FJ1478M','FJ1512','FJ1512M']},
 triceps:{name:'Triceps brachii',region:'Upper arm',group:'upper',view:'Posterior',info:'The large posterior upper-arm muscle and primary extensor of the elbow.',files:['FJ1477','FJ1477M','FJ1479','FJ1479M']},
 trapezius:{name:'Trapezius',region:'Upper back',group:'torso',view:'Posterior',info:'A broad superficial muscle that moves and stabilizes the shoulder blades and supports the neck.',files:['FJ1520','FJ1520M','FJ1521','FJ1521M','FJ1554','FJ1554M']},
 gluteus:{name:'Gluteus maximus',region:'Hip',group:'lower',view:'Posterior',info:'The largest gluteal muscle, powering hip extension and outward rotation.',files:['FJ1418','FJ1418M']},
 quadriceps:{name:'Quadriceps femoris',region:'Thigh',group:'lower',view:'Anterior',info:'Front-thigh muscles that extend the knee.',files:['FJ1433','FJ1433M','FJ1442','FJ1442M']},
 adductor:{name:'Adductor longus',region:'Thigh',group:'lower',view:'Anterior / medial',info:'A medial thigh muscle that draws the thigh toward the body midline.',files:['FJ1402','FJ1402M']},
 hamstrings:{name:'Biceps femoris',region:'Thigh',group:'lower',view:'Posterior',info:'A posterior thigh muscle that flexes the knee and extends the hip.',files:['FJ1395','FJ1395M']},
 tibialis:{name:'Tibialis anterior',region:'Lower leg',group:'lower',view:'Anterior',info:'Runs along the shin and dorsiflexes the ankle, lifting the foot upward.',files:['FJ1439','FJ1439M']},
 gastrocnemius:{name:'Gastrocnemius',region:'Calf',group:'lower',view:'Posterior',info:'The prominent two-headed calf muscle that plantarflexes the ankle and assists knee flexion.',files:['FJ1394','FJ1394M','FJ1397','FJ1397M']},
 soleus:{name:'Soleus',region:'Calf',group:'lower',view:'Posterior / lateral',info:'A deep calf muscle important for standing posture and plantarflexing the foot.',files:['FJ1437','FJ1437M']}
};
const STRUCTURES={}, muscleOrder=Object.keys(MUSCLES);for(const [key,m] of Object.entries(MUSCLES))STRUCTURES[key]={...m,layer:'muscle'};
const canvas=document.querySelector('#atlas-canvas'),viewport=document.querySelector('#viewport'),loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);
const modelScale=.00605,modelCenterZ=801,physique={height:193,weight:80,definition:62};let scene,camera,renderer,controls,body,muscleGroup,boneGroup,likenessGroup,privateLikenessGroup,recordMarker=null,selected=null,hovered=null,parts=[],injuryPins=[],activeLayer='muscle',viewTween=0,pointerStart=null,logPointMode=false;
function regionForBone(name){if(/skull|frontal|ethmoid|sphenoid|vomer|parietal|temporal|occipital|maxilla|mandible|nasal|zygomatic|lacrimal|palatine|hyoid/.test(name))return['Head','head'];if(/rib|sternum|manubrium|xiphoid|vertebra/.test(name))return['Torso','torso'];if(/clavicle|scapula|humerus|radius|ulna|carpal|metacarpal|phalanx.*finger|thumb|capitate|hamate|lunate|pisiform|scaphoid|trapezi/.test(name))return['Upper limb','upper'];return['Lower limb','lower']}
function boneInfo(name){if(name.includes('phalanx'))return 'A named digital bone in the hand or foot.';if(name.includes('vertebra'))return 'One of the vertebrae forming the spinal column.';if(name.includes('rib'))return 'A curved bone contributing to the thoracic cage.';return `The ${name}, shown in its anatomical position.`}
function keyForBone(name,index){return `bone-${index}-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}
function material(layer){return layer==='bone'?new THREE.MeshPhysicalMaterial({color:0xe8eee9,roughness:.5,metalness:.02,clearcoat:.18,emissive:0x102426,emissiveIntensity:.16}):new THREE.MeshPhysicalMaterial({color:0x9fc1c4,roughness:.58,metalness:.02,clearcoat:.18,emissive:0x073238,emissiveIntensity:.2})}
function wrapperFor(obj,key='body'){const wrapper=new THREE.Group();wrapper.rotation.x=-Math.PI/2;wrapper.scale.set(modelScale*.82,modelScale*1.055,modelScale*.86);wrapper.position.y=-modelCenterZ*modelScale*1.055;wrapper.userData.baseScale=wrapper.scale.clone();wrapper.userData.structureKey=key;wrapper.add(obj);return wrapper}
function prepare(obj,key,layer){obj.traverse(c=>{if(!c.isMesh)return;c.geometry.computeVertexNormals();c.material=material(layer);c.userData.key=key;c.userData.layer=layer;parts.push(c)});return wrapperFor(obj,key)}

function applyPhysique(){
 const mass=THREE.MathUtils.clamp((physique.weight-65)/45,0,1),lean=THREE.MathUtils.clamp(physique.definition/100,0,1);
 const width=.91+mass*.22,depth=.93+mass*.18;
 for(const group of [muscleGroup,boneGroup])for(const wrapper of group?.children||[]){const base=wrapper.userData.baseScale;if(!base)continue;const key=wrapper.userData.structureKey,m=STRUCTURES[key],region=m?.group||'body';let regional=1;if(region==='upper')regional=.97+mass*.11;if(region==='torso')regional=.98+mass*.08;if(region==='lower')regional=.98+mass*.09;wrapper.scale.set(base.x*width*regional,base.y,base.z*depth*regional)}
 parts.forEach(mesh=>{if(mesh.userData.layer!=='muscle')return;mesh.material.roughness=.68-lean*.34;mesh.material.clearcoat=.12+lean*.34;mesh.material.emissiveIntensity=.18+lean*.13});
 body?.updateMatrixWorld(true);document.documentElement.style.setProperty('--physique-definition',String(lean));
 const out=document.querySelector('.physique-readout');if(out)out.textContent=`${physique.weight} KG · ${physique.definition}% DEFINITION`;
}
function buildPhysiqueControl(){const panel=document.createElement('section');panel.className='physique-control';panel.setAttribute('aria-label','Illustrative physique preview');panel.innerHTML=`<button class="physique-toggle" type="button" aria-expanded="false">PHYSIQUE PREVIEW <span>＋</span></button><div class="physique-panel" hidden><div class="physique-copy"><b>193 CM · LEAN FIT BASELINE</b><small>Illustrative model — not a body scan or muscle measurement.</small></div><label>BODYWEIGHT <output>80 KG</output><input data-physique="weight" type="range" min="65" max="110" value="80" step="1"></label><label>DEFINITION / COMPOSITION PREVIEW <output>62%</output><input data-physique="definition" type="range" min="20" max="100" value="62" step="1"></label><p>Weight changes the mesh frame; definition changes surface emphasis. They are separate previews.</p><span class="physique-readout">80 KG · 62% DEFINITION</span></div>`;viewport.parentNode.insertBefore(panel,viewport.nextSibling);const toggle=panel.querySelector('.physique-toggle'),drawer=panel.querySelector('.physique-panel');toggle.onclick=()=>{const open=drawer.hidden;drawer.hidden=!open;toggle.setAttribute('aria-expanded',String(open));toggle.querySelector('span').textContent=open?'−':'＋'};panel.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{physique[input.dataset.physique]=Number(input.value);input.previousElementSibling.textContent=input.dataset.physique==='weight'?`${input.value} KG`:`${input.value}%`;applyPhysique()}))}
function tubeBetween(a,b,r,color,opacity=.8){const mid=a.clone().lerp(b,.5);mid.y+=.035;const curve=new THREE.CatmullRomCurve3([a,mid,b]);return new THREE.Mesh(new THREE.TubeGeometry(curve,20,r,8,false),new THREE.MeshPhysicalMaterial({color,transparent:true,opacity,roughness:.42,clearcoat:.35,depthWrite:opacity>.5}))}
function buildFeet(envelope){
 body.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(envelope),min=body.worldToLocal(box.min.clone()),max=body.worldToLocal(box.max.clone()),height=max.y-min.y,width=max.x-min.x;
 const footMaterial=new THREE.MeshPhysicalMaterial({color:0x83a9ad,roughness:.72,metalness:.01,clearcoat:.08,emissive:0x062b30,emissiveIntensity:.14,transparent:true,opacity:.46,depthWrite:false});
 const footGroup=new THREE.Group();footGroup.name='complete-feet';const ankleY=min.y+height*.035,side=width*.092;
 [-1,1].forEach(sign=>{const foot=new THREE.Group();foot.name=sign<0?'anatomical-left-foot':'anatomical-right-foot';foot.position.set(sign*side,ankleY,.07);foot.rotation.y=sign*.035;
  const ankle=new THREE.Mesh(new THREE.CylinderGeometry(width*.027,width*.038,height*.05,18),footMaterial);ankle.position.y=height*.005;foot.add(ankle);
  const sole=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),footMaterial);sole.scale.set(width*.055,height*.018,width*.14);sole.position.set(sign*width*.006,-height*.018,width*.105);foot.add(sole);
  const forefoot=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),footMaterial);forefoot.scale.set(width*.064,height*.015,width*.075);forefoot.position.set(sign*width*.008,-height*.021,width*.205);foot.add(forefoot);
  const toeSizes=[1,.88,.76,.66,.58];for(let i=0;i<5;i++){const toe=new THREE.Mesh(new THREE.SphereGeometry(1,16,10),footMaterial);const lateral=(i-2)*width*.021*sign,scale=width*.023*toeSizes[i];toe.scale.set(scale,height*.01,scale*1.2);toe.position.set(lateral,-height*(.023+i*.0005),width*(.265-i*.006));foot.add(toe)}
  footGroup.add(foot)});
 likenessGroup.add(footGroup);footGroup.userData.completeFeet=true;
}
function buildLikenessDetails(envelope){
 likenessGroup=new THREE.Group();privateLikenessGroup=new THREE.Group();privateLikenessGroup.visible=false;body.add(likenessGroup,privateLikenessGroup);buildFeet(envelope);
 const clavicles=parts.filter(p=>p.userData.layer==='bone'&&/clavicle/i.test(STRUCTURES[p.userData.key]?.name||''));
 clavicles.forEach(part=>{const box=new THREE.Box3().setFromObject(part),a=box.min.clone(),b=box.max.clone();body.worldToLocal(a);body.worldToLocal(b);const left=/left clavicle/i.test(STRUCTURES[part.userData.key]?.name||'');
   const ridge=tubeBetween(new THREE.Vector3(a.x,(a.y+b.y)/2,b.z+.025),new THREE.Vector3(b.x,(a.y+b.y)/2,a.z+.025),.018,0xffffff,.42);likenessGroup.add(ridge);
   if(left){const start=a.clone().lerp(b,.16),end=a.clone().lerp(b,.86),front=Math.max(a.z,b.z)+.12;start.y+=.018;end.y-=.012;start.z=front;end.z=front;const scar=tubeBetween(start,end,.014,0xb59662,1);scar.material.emissive=new THREE.Color(0x5c340d);scar.material.emissiveIntensity=.7;scar.renderOrder=4;privateLikenessGroup.add(scar);const prominence=new THREE.Mesh(new THREE.SphereGeometry(.05,18,12),new THREE.MeshPhysicalMaterial({color:0xfff7e7,roughness:.32,clearcoat:.5}));prominence.position.copy(start.clone().lerp(end,.58));prominence.scale.set(1.25,.72,.82);prominence.renderOrder=4;privateLikenessGroup.add(prominence)}
 });
 window.addEventListener('health:record-ready',e=>{privateLikenessGroup.visible=Boolean(e.detail?.bodyLikeness?.anatomicalLeftClavicle)});window.addEventListener('health:record-cleared',()=>{privateLikenessGroup.visible=false});
}
async function buildBody(){body=new THREE.Group();body.rotation.z=-.012;scene.add(body);muscleGroup=new THREE.Group();boneGroup=new THREE.Group();body.add(muscleGroup,boneGroup);const progress=document.querySelector('#load-progress'),bar=progress.querySelector('i'),label=progress.querySelector('span');let loaded=0;const showProgress=e=>{if(e.total){loaded=Math.min(95,loaded+Math.round(e.loaded/e.total*45));bar.style.width=loaded+'%';label.textContent=`LOADING ANATOMY · ${loaded}%`}};
 const [muscleGLB,skeletonGLB]=await Promise.all([loader.loadAsync('./models/bodyparts3d.glb',showProgress),loader.loadAsync('./models/skeleton.glb',showProgress)]);const fileToKey={};for(const [key,m] of Object.entries(MUSCLES))for(const f of m.files)fileToKey[f]=key;
 muscleGLB.scene.children.slice().forEach(node=>{const all=['FJ2810',...Object.values(MUSCLES).flatMap(m=>m.files)].sort((a,b)=>b.length-a.length),id=all.find(f=>node.name.endsWith(f)),key=fileToKey[id];if(id==='FJ2810'){const w=wrapperFor(node);node.traverse(c=>{if(!c.isMesh)return;c.material=new THREE.MeshBasicMaterial({color:0x70949a,transparent:true,opacity:.48,depthWrite:false,side:THREE.DoubleSide});c.renderOrder=-1});muscleGroup.add(w);muscleGroup.userData.envelope=w}else if(key)muscleGroup.add(prepare(node,key,'muscle'))});
 const boneNodes=[];skeletonGLB.scene.traverse(node=>{if(node.isMesh)boneNodes.push(node)});boneNodes.forEach((node,i)=>{const name=(node.name||`Bone ${i}`).replace(/_/g,' ').replace(/ \(\d+\)$/,'');const key=keyForBone(name,i),[region,group]=regionForBone(name.toLowerCase());STRUCTURES[key]={name:name.replace(/^./,c=>c.toUpperCase()),region,group,view:'Bone',info:boneInfo(name),layer:'bone'};boneGroup.add(prepare(node,key,'bone'))});boneGroup.visible=false;buildLikenessDetails(muscleGroup.userData.envelope);createRecordMarker();applyPhysique();bar.style.width='100%';label.textContent='ANATOMY READY';renderList();progress.classList.add('done');setTimeout(()=>progress.hidden=true,550)}
function pinMesh(point,{label='Injury point',severity=5,status='ongoing'}={}){const pin=new THREE.Mesh(new THREE.SphereGeometry(.09,20,14),new THREE.MeshPhysicalMaterial({color:0xff3b30,emissive:0xc80f08,emissiveIntensity:2.2,roughness:.2,clearcoat:1,transparent:true,opacity:status==='resolved'?.48:.96}));pin.position.set(point.x,point.y,point.z);pin.userData.injuryPin=true;pin.userData.label=label;pin.userData.severity=severity;body.add(pin);injuryPins.push(pin);return pin}
function clearInjuryPins(){injuryPins.filter(pin=>pin!==recordMarker).forEach(pin=>{body.remove(pin);pin.geometry.dispose();pin.material.dispose()});injuryPins=recordMarker?[recordMarker]:[]}
function recordInjuryMarker(injury){const matcher=injury?.region==='left-clavicle'?/^left clavicle$/i:null;if(!matcher)return null;const targets=parts.filter(p=>p.userData.layer==='bone'&&matcher.test(STRUCTURES[p.userData.key]?.name||''));if(!targets.length)return null;const point=new THREE.Vector3();targets.forEach(p=>point.add(new THREE.Box3().setFromObject(p).getCenter(new THREE.Vector3())));point.multiplyScalar(1/targets.length);body.worldToLocal(point);const pin=pinMesh(point,{label:injury.label,status:injury.status});pin.scale.setScalar(2.1);pin.userData.recordInjury=true;pin.userData.injuryId=injury.id;pin.userData.year=injury.year||'';pin.userData.dateCertainty=injury.dateCertainty||'';return pin}
function createRecordMarker(){body.updateMatrixWorld(true);const keys=Object.keys(STRUCTURES).filter(k=>/left first metatarsal bone|proximal phalanx of left big toe/i.test(STRUCTURES[k].name));const targets=parts.filter(p=>keys.includes(p.userData.key));if(!targets.length)return;const point=new THREE.Vector3();targets.forEach(p=>point.add(new THREE.Box3().setFromObject(p).getCenter(new THREE.Vector3())));point.multiplyScalar(1/targets.length);body.worldToLocal(point);recordMarker=pinMesh(point,{label:'Authenticated left first MTP injury',severity:7});recordMarker.visible=false;recordMarker.userData.recordMarker=true;window.addEventListener('health:record-ready',e=>{recordMarker.visible=e.detail?.region==='left-first-mtp'||Array.isArray(e.detail?.injuries)&&e.detail.injuries.some(x=>x?.region==='left-first-mtp')});window.addEventListener('health:record-cleared',()=>{recordMarker.visible=false;clearInjuryPins()});window.addEventListener('health:journal-points-ready',e=>{clearInjuryPins();recordMarker.visible=recordMarker.visible===true;(e.detail?.recordInjuries||[]).forEach(recordInjuryMarker);(e.detail?.points||[]).forEach(x=>x?.point&&pinMesh(x.point,x))});window.addEventListener('health:journal-points-cleared',()=>{clearInjuryPins();recordMarker.visible=false})}
async function init(){try{buildPhysiqueControl();renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.14;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(27,1,.1,100);camera.position.set(0,.15,23.5);controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=8;controls.maxDistance=32;controls.target.set(0,0,0);controls.enablePan=false;controls.autoRotate=false;controls.saveState();scene.add(new THREE.HemisphereLight(0xdffcff,0x123035,4.4));const key=new THREE.DirectionalLight(0xffffff,6);key.position.set(-5,9,8);scene.add(key);const fill=new THREE.DirectionalLight(0x9eeef4,2.6);fill.position.set(4,-1,6);scene.add(fill);const rim=new THREE.DirectionalLight(0x6fefff,4.5);rim.position.set(6,2,-7);scene.add(rim);const gold=new THREE.PointLight(0xb59662,2.2,20);gold.position.set(-5,-2,4);scene.add(gold);await buildBody();resize();fitCameraToBody();controls.saveState();addEvents();animate();window.__HEALTH_ATLAS__={ready:true,muscleCount:muscleOrder.length,boneCount:Object.values(STRUCTURES).filter(x=>x.layer==='bone').length,get selected(){return selected},get hovered(){return hovered?.userData?.key||null},get layer(){return activeLayer},get logPointMode(){return logPointMode},get injuryPinCount(){return injuryPins.filter(x=>x.visible).length},get markerVisible(){return recordMarker?.visible===true},get state(){return{camera:camera.position.toArray(),target:controls.target.toArray(),autoRotate:false,controlsAutoRotate:controls.autoRotate,privateLikenessVisible:privateLikenessGroup?.visible===true,likenessVisible:likenessGroup?.visible===true}},view:setView,parts:parts.length,project:projectStructure,projectAll:projectStructures,figureFrame,projectMarker(){if(!recordMarker)return null;const r=canvas.getBoundingClientRect(),p=recordMarker.getWorldPosition(new THREE.Vector3()).project(camera);return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}},projectRecordInjury(id){const pin=injuryPins.find(x=>x.userData.injuryId===id);if(!pin)return null;const r=canvas.getBoundingClientRect(),p=pin.getWorldPosition(new THREE.Vector3()).project(camera);return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}},setLayer};document.documentElement.dataset.atlasReady='true'}catch(e){console.error(e);document.querySelector('#webgl-fallback').hidden=false;bindDirectory();window.__HEALTH_ATLAS__={ready:false,error:String(e)}}}
function figureCorners(){body.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(body),{min,max}=box;return[...Array(8)].map((_,i)=>new THREE.Vector3(i&1?max.x:min.x,i&2?max.y:min.y,i&4?max.z:min.z))}
function fitCameraToBody(){if(!body||!viewport.clientWidth||!viewport.clientHeight)return;const corners=figureCorners(),box=new THREE.Box3().setFromPoints(corners),center=box.getCenter(new THREE.Vector3()),direction=camera.position.clone().sub(controls.target).normalize(),up=camera.up.clone().normalize(),right=new THREE.Vector3().crossVectors(direction,up).normalize();const fittedUp=new THREE.Vector3().crossVectors(right,direction).normalize();const verticalPadding=Math.max(28,viewport.clientHeight*.065),horizontalPadding=Math.max(20,viewport.clientWidth*.055),limitY=1-2*verticalPadding/viewport.clientHeight,limitX=1-2*horizontalPadding/viewport.clientWidth,tanY=Math.tan(THREE.MathUtils.degToRad(camera.fov*.5)),tanX=tanY*camera.aspect;let distance=0;for(const corner of corners){const offset=corner.clone().sub(center),depth=offset.dot(direction);distance=Math.max(distance,depth+Math.abs(offset.dot(fittedUp))/(tanY*limitY),depth+Math.abs(offset.dot(right))/(tanX*limitX))}distance*=1.015;controls.target.copy(center);camera.position.copy(center).addScaledVector(direction,distance);camera.near=Math.max(.05,distance-box.getSize(new THREE.Vector3()).length());camera.far=distance+box.getSize(new THREE.Vector3()).length()*2;camera.updateProjectionMatrix();controls.update()}
function figureFrame(){const r=canvas.getBoundingClientRect(),points=figureCorners().map(point=>point.project(camera)),xs=points.map(p=>r.left+(p.x+1)*r.width/2),ys=points.map(p=>r.top+(1-p.y)*r.height/2);return{left:Math.min(...xs),right:Math.max(...xs),top:Math.min(...ys),bottom:Math.max(...ys),canvas:{left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height}}}
function resize(){if(!renderer)return;const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();if(body)fitCameraToBody()}
function activeParts(){return parts.filter(p=>p.userData.layer===activeLayer)}function intersection(x,y,includePins=true){const r=canvas.getBoundingClientRect(),mouse=new THREE.Vector2((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);return ray.intersectObjects(includePins?[...injuryPins.filter(p=>p.visible),...activeParts()]:activeParts(),false)[0]||null}function hit(x,y){return intersection(x,y)?.object||null}
function projectStructure(key){return projectStructures(key)[0]||null}function projectStructures(key){const r=canvas.getBoundingClientRect();return parts.filter(p=>p.userData.key===key).map(target=>{const p=new THREE.Box3().setFromObject(target).getCenter(new THREE.Vector3()).project(camera);return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}})}
function addEvents(){window.addEventListener('resize',resize);window.addEventListener('health:log-mode-changed',e=>{logPointMode=e.detail?.active===true;document.documentElement.classList.toggle('injury-log-active',logPointMode)});canvas.addEventListener('pointermove',e=>{if(e.buttons)return;hovered=hit(e.clientX,e.clientY);canvas.style.cursor=logPointMode||hovered?'crosshair':'grab';const t=document.querySelector('#tooltip');if(hovered){t.style.display='block';t.style.left=e.offsetX+'px';t.style.top=e.offsetY+'px';t.textContent=hovered.userData.injuryPin?`${hovered.userData.label.toUpperCase()}${hovered.userData.year?` · ${hovered.userData.year.toUpperCase()}`:''} · INJURY`:STRUCTURES[hovered.userData.key].name.toUpperCase()}else t.style.display='none'});canvas.addEventListener('pointerdown',e=>pointerStart={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(pointerStart&&Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)<8){if(logPointMode){const h=intersection(e.clientX,e.clientY,false);if(h){const p=body.worldToLocal(h.point.clone()),m=STRUCTURES[h.object.userData.key];window.dispatchEvent(new CustomEvent('health:point-selected',{detail:{x:p.x,y:p.y,z:p.z,structureKey:h.object.userData.key,structureName:m.name,layer:m.layer}}))}}else{const m=hit(e.clientX,e.clientY);if(m?.userData.recordMarker)window.dispatchEvent(new CustomEvent('health:focus-record',{detail:{region:'left-first-mtp'}}));else if(m?.userData.injuryPin)window.dispatchEvent(new CustomEvent('health:focus-injury',{detail:{id:m.userData.injuryId,label:m.userData.label}}));else if(m)selectStructure(m.userData.key)}}pointerStart=null});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>setLayer(b.dataset.layer));document.querySelector('#zoom-in').onclick=()=>zoom(-1.8);document.querySelector('#zoom-out').onclick=()=>zoom(1.8);document.querySelector('#focus-button').onclick=()=>selected&&focusSelected();document.querySelector('#close-inspector').onclick=clearSelection;bindDirectory()}
function bindDirectory(){document.querySelector('#search').addEventListener('input',filterList);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filterList()})}
function setLayer(layer){activeLayer=layer;muscleGroup.visible=layer==='muscle';boneGroup.visible=layer==='bone';if(likenessGroup)likenessGroup.visible=layer==='muscle';hovered=null;clearSelection();fitCameraToBody();document.querySelectorAll('[data-layer]').forEach(b=>{const on=b.dataset.layer===layer;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});renderList()}
function setView(view){document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));cancelAnimationFrame(viewTween);controls.enableDamping=false;controls.reset();if(view==='reset')clearSelection();if(view==='back')camera.position.copy(controls.target).add(new THREE.Vector3(0,0,-camera.position.distanceTo(controls.target)));else camera.position.copy(controls.target).add(new THREE.Vector3(0,0,camera.position.distanceTo(controls.target)));fitCameraToBody();controls.update();controls.enableDamping=true}
function zoom(delta){const direction=camera.position.clone().sub(controls.target).normalize(),distance=THREE.MathUtils.clamp(camera.position.distanceTo(controls.target)+delta,8,32);camera.position.copy(controls.target).addScaledVector(direction,distance);controls.update()}
function tweenCamera(destination,target){const p0=camera.position.clone(),t0=controls.target.clone(),start=performance.now();(function step(now){const p=Math.min(1,(now-start)/520),q=1-Math.pow(1-p,3);camera.position.lerpVectors(p0,destination,q);controls.target.lerpVectors(t0,target,q);controls.update();if(p<1)viewTween=requestAnimationFrame(step)})(start)}
function selectStructure(key){const m=STRUCTURES[key];if(!m)return;selected=key;const same=Object.keys(STRUCTURES).filter(k=>STRUCTURES[k].layer===activeLayer),i=same.indexOf(key)+1;document.querySelector('#muscle-number').textContent=String(i).padStart(2,'0');document.querySelector('#muscle-name').textContent=m.name;document.querySelector('#muscle-meta').textContent=m.info;document.querySelector('#muscle-region').textContent=m.region.toUpperCase();document.querySelector('#muscle-view').textContent=m.layer.toUpperCase();document.querySelector('#focus-button').disabled=false;document.querySelectorAll('.muscle-item').forEach(el=>el.classList.toggle('selected',el.dataset.key===key))}
function clearSelection(){selected=null;document.querySelector('#muscle-number').textContent='00';document.querySelector('#muscle-name').textContent='Select a structure';document.querySelector('#muscle-meta').textContent='Touch the illuminated body to begin.';document.querySelector('#muscle-region').textContent='—';document.querySelector('#muscle-view').textContent='—';document.querySelector('#focus-button').disabled=true;document.querySelectorAll('.muscle-item').forEach(el=>el.classList.remove('selected'))}
function focusSelected(){const targets=parts.filter(p=>p.userData.key===selected);if(!targets.length)return;const box=new THREE.Box3();targets.forEach(p=>box.expandByObject(p));const c=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length(),dir=camera.position.clone().sub(controls.target).normalize();tweenCamera(c.clone().addScaledVector(dir,Math.max(8,size*3.2)),c)}
function animate(){requestAnimationFrame(animate);const pulse=1.6+Math.sin(performance.now()*.005)*.25;for(const p of activeParts()){const on=p.userData.key===selected,over=p===hovered,base=p.userData.layer==='bone'?0xe8eee9:0x9fc1c4;p.material.color.setHex(on?0xd8fdff:over?0xffffff:base);p.material.emissive.setHex(on?0x19dff5:over?0x1c6872:p.userData.layer==='bone'?0x18282a:0x0b2b30);p.material.emissiveIntensity=on?pulse:over?.8:.26}controls.update();renderer.render(scene,camera)}
function renderList(){const list=document.querySelector('#muscle-list'),keys=Object.keys(STRUCTURES).filter(k=>STRUCTURES[k].layer===activeLayer).sort((a,b)=>STRUCTURES[a].name.localeCompare(STRUCTURES[b].name));list.innerHTML=keys.map((k,i)=>{const m=STRUCTURES[k];return `<button class="muscle-item" data-key="${k}" data-group="${m.group}" data-search="${(m.name+' '+m.region).toLowerCase()}"><span class="idx">${String(i+1).padStart(2,'0')}</span><span><b>${m.name}</b><small>${m.region.toUpperCase()} · ${m.layer.toUpperCase()}</small></span><span class="arrow">↗</span></button>`}).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{selectStructure(b.dataset.key);viewport.scrollIntoView({behavior:'smooth',block:'center'})});filterList()}
function filterList(){const q=document.querySelector('#search').value.toLowerCase().trim(),g=document.querySelector('[data-filter].active')?.dataset.filter||'all';document.querySelectorAll('.muscle-item').forEach(el=>el.hidden=!(el.dataset.search.includes(q)&&(g==='all'||el.dataset.group===g)))}
renderList();init();