const root=document.querySelector('.brain-overlay');
if(root){
  const copy={energy:['Energy','How physiologically energetic you reported feeling.'],focus:['Focus / clarity','How readily you can get to work and sustain a Pomodoro.'],stress:['Low stress','Reverse-scored from stress: 0 stress earns 10/10.'],calm:['Calm','How content, rested and low in felt stress you feel.'],happiness:['Happiness','Your self-reported contentment versus frustration.']};
  let latest=null;
  function paint(entry){latest=entry?.answers||null;root.classList.toggle('has-data',!!latest);for(const path of root.querySelectorAll('[data-region]')){const key=path.dataset.region,value=latest?(key==='stress'?10-Number(latest.stress):Number(latest[key])):0;path.style.setProperty('--region-level',Math.max(0,Math.min(1,value/10)))}if(latest){const movement=['done','planned','recovery'].includes(latest.movement)?10:0,values=[Math.min(Number(latest.sleep||0)/8,1)*10,Number(latest.energy),Number(latest.focus),10-Number(latest.stress),Number(latest.calm),Number(latest.happiness),movement],strength=Math.max(0,Math.min(1,values.reduce((sum,value)=>sum+(Number.isFinite(value)?value:0),0)/70));root.style.setProperty('--synapse-strength',strength);root.style.setProperty('--synapse-opacity',(0.18+strength*0.82).toFixed(3));root.style.setProperty('--synapse-rate',`${(3.4-strength*1.8).toFixed(2)}s`)}else{root.style.removeProperty('--synapse-strength');root.style.removeProperty('--synapse-opacity');root.style.removeProperty('--synapse-rate')}}
  document.addEventListener('health:checkin',e=>paint(e.detail));
  const dismiss=()=>{const pop=root.querySelector('.brain-popover');pop.hidden=true;pop.replaceChildren();root.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed','false'))};
  root.querySelectorAll('button').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();const key=button.dataset.brainRegion,[title,description]=copy[key],raw=latest?.[key],score=latest?(key==='stress'?10-Number(raw):Number(raw)):null,pop=root.querySelector('.brain-popover');pop.innerHTML=`<b>${title}</b><span>${score==null?'No check-in yet':`${score}/10 contribution`}</span><small>${description}</small>`;pop.hidden=false;root.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)))}));
  document.querySelector('#atlas-canvas')?.addEventListener('pointerdown',dismiss);
  document.addEventListener('pointerdown',event=>{if(!root.contains(event.target))dismiss()});
  document.addEventListener('keydown',event=>{if(event.key==='Escape')dismiss()});
  let hydrated=false;
  const syncZoomDetail=()=>{let detail=false;const state=window.__HEALTH_ATLAS__?.state;if(state){const distance=Math.hypot(...state.camera.map((value,index)=>value-state.target[index]));detail=distance<=14;root.classList.toggle('zoom-detail',detail)}if(!hydrated&&window.__HEALTH_ENERGY__){hydrated=true;const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,entry=window.__HEALTH_ENERGY__.read().find(item=>item.date===today);paint(entry||null)}root.querySelector('.synapses').style.setProperty('opacity',detail&&latest?root.style.getPropertyValue('--synapse-opacity'):'0','important')};
  paint(null);
  setInterval(syncZoomDetail,180);syncZoomDetail();
}
