import * as THREE from './vendor/three.module.min.js';
import { OrbitControls } from './vendor/OrbitControls.js';

export const BRAIN_STORAGE_KEY='novaire-health-energy-checkins-v1';
export const BRAIN_EVENT='health:brain-self-report';
export const BRAIN_PARTS={
  frontal:{name:'Frontal lobe',group:'Cerebrum',view:'Anterior',description:'The front portion of each cerebral hemisphere.'},
  parietal:{name:'Parietal lobe',group:'Cerebrum',view:'Superior',description:'The upper rear portion of each cerebral hemisphere.'},
  temporal:{name:'Temporal lobe',group:'Cerebrum',view:'Lateral',description:'The lower lateral portion of each cerebral hemisphere.'},
  occipital:{name:'Occipital lobe',group:'Cerebrum',view:'Posterior',description:'The rear portion of each cerebral hemisphere.'},
  cerebellum:{name:'Cerebellum',group:'Hindbrain',view:'Posterior / inferior',description:'The densely folded structure beneath the occipital lobes.'},
  brainstem:{name:'Brainstem',group:'Brainstem',view:'Inferior',description:'The stalk-like structure connecting the brain with the spinal cord.'}
};
const clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
export function expressiveLevel(entry){const a=entry?.answers;if(!a)return null;const values=[a.energy,a.focus].filter(Number.isFinite).map(n=>clamp(n,0,10));const sleep=entry?.foundations?.sleepHours??a.sleep;if(Number.isFinite(sleep))values.push(Math.min(clamp(sleep,0,24)/8,1)*10);return values.length?values.reduce((s,n)=>s+n,0)/(values.length*10):null}
export function latestLocalEntry(storage=globalThis.localStorage){try{const entries=JSON.parse(storage?.getItem(BRAIN_STORAGE_KEY)||'[]');return Array.isArray(entries)&&entries.length?entries.filter(e=>e?.answers).sort((a,b)=>String(a.date).localeCompare(String(b.date))).at(-1)||null:null}catch{return null}}

const root=typeof document==='undefined'?null:document.querySelector('[data-brain-atlas]');
if(root){
  root.classList.add('brain-atlas');
  root.innerHTML=`<div class="brain-atlas__head"><div><p class="brain-atlas__eyebrow">HEALTH ATLAS / 02</p><h2>The inner<br><em>command deck</em></h2></div><p class="brain-atlas__intro">Rotate, zoom and select an anatomical structure. Its light is an expressive reflection of today’s self-reported energy, focus and rest—not a scan.</p></div><div class="brain-atlas__deck"><div class="brain-atlas__viewport" role="application" tabindex="0" aria-label="Interactive three-dimensional brain. Drag to rotate, pinch or scroll to zoom, and select a labeled structure."><canvas></canvas><div class="brain-atlas__halo" aria-hidden="true"></div><div class="brain-atlas__orientation"><span>SUPERIOR</span><span>INFERIOR</span></div><div class="brain-atlas__loading" role="status">ASSEMBLING ANATOMY</div><div class="brain-atlas__tooltip" role="status"></div></div><aside class="brain-atlas__panel" aria-live="polite"><p class="brain-atlas__eyebrow">SELECTED ANATOMY</p><strong class="brain-atlas__number">00</strong><h3>Select a structure</h3><p class="brain-atlas__description">Choose a label or touch the model.</p><dl><div><dt>GROUP</dt><dd>—</dd></div><div><dt>VIEW</dt><dd>—</dd></div></dl><button type="button" data-brain-reset>RESET VIEW</button></aside><nav class="brain-atlas__labels" aria-label="Brain structures">${Object.entries(BRAIN_PARTS).map(([key,p])=>`<button type="button" data-brain-part="${key}" aria-pressed="false"><i></i><span>${p.name}</span></button>`).join('')}</nav><div class="brain-atlas__zoom"><button type="button" data-brain-zoom="in" aria-label="Zoom in">+</button><span>ZOOM</span><button type="button" data-brain-zoom="out" aria-label="Zoom out">−</button></div></div><div class="brain-atlas__signal"><div><span>EXPRESSIVE LIGHT</span><strong data-brain-signal>NEUTRAL · NO CHECK-IN</strong></div><div class="brain-atlas__meter" aria-hidden="true"><i></i></div><p><b>SELF-REPORT VISUALIZATION</b> Brightness responds uniformly to energy, focus and sleep you explicitly logged. It is <b>not measured brain activity, a diagnosis, regional function, or inferred neuroscience.</b></p></div><p class="brain-atlas__source">Stylized educational anatomy built from procedural geometry. Major external regions are labeled; proportions are illustrative, not clinical.</p>`;
  const canvas=root.querySelector('canvas'),viewport=root.querySelector('.brain-atlas__viewport'),tooltip=root.querySelector('.brain-atlas__tooltip');
  let renderer,scene,camera,controls,brain,selected=null,hovered=null,pointer=null,level=null,raf=0;
  const pickables=[];
  const palette={frontal:0x8fbfc2,parietal:0x82adb1,temporal:0x739da3,occipital:0x688d95,cerebellum:0x9a8b68,brainstem:0x718789};
  function mat(key){return new THREE.MeshStandardMaterial({color:palette[key],roughness:.76,metalness:0,emissive:new THREE.Color(0x071719),emissiveIntensity:.08})}
  function foldedGeometry(detail=0){const geometry=new THREE.SphereGeometry(1,96-detail*8,68-detail*5);const pos=geometry.attributes.position,v=new THREE.Vector3();for(let i=0;i<pos.count;i++){v.fromBufferAttribute(pos,i);const longitude=Math.atan2(v.z,v.x),latitude=Math.asin(v.y/Math.max(.0001,v.length()));const sweep=longitude*10+Math.sin(latitude*5)*2.4;const fold=Math.sin(sweep)*Math.cos(latitude*12)*(.065+detail*.012)+Math.sin(longitude*17-latitude*9)*(.025+detail*.006);v.multiplyScalar(1+fold);pos.setXYZ(i,v.x,v.y,v.z)}pos.needsUpdate=true;geometry.computeVertexNormals();return geometry}
  function ellipsoid(key,pos,scale){const mesh=new THREE.Mesh(foldedGeometry(key==='cerebellum'?1:0),mat(key));mesh.position.set(...pos);mesh.scale.set(...scale);mesh.userData.key=key;brain.add(mesh);pickables.push(mesh);return mesh}
  function sulcus(points,r=.014,color=0x254548,opacity=.88){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));const tube=new THREE.Mesh(new THREE.TubeGeometry(curve,72,r,10,false),new THREE.MeshStandardMaterial({color,roughness:1,transparent:true,opacity,depthWrite:false}));brain.add(tube)}
  function buildBrain(){brain=new THREE.Group();brain.rotation.set(-.04,.08,-.02);brain.scale.set(1.02,1,.94);scene.add(brain);
    for(const side of [-1,1]){const x=side*.55;
      ellipsoid('frontal',[x,.18,.55],[.76,.96,1.08]);ellipsoid('parietal',[x,.5,-.28],[.77,.78,.91]);ellipsoid('temporal',[x,-.43,.02],[.72,.51,.86]);ellipsoid('occipital',[x,.08,-.94],[.68,.7,.66]);
    }
    for(let z=-.88;z<=.63;z+=.2)sulcus([[-.06,.91-Math.abs(z)*.15,z],[0,.79-Math.abs(z)*.1,z-.05],[.06,.91-Math.abs(z)*.15,z]],.015,0x061012,1);
    ellipsoid('cerebellum',[0,-.62,-1.08],[.83,.46,.52]);for(let i=-5;i<=5;i++)sulcus([[-.68,-.62+i*.057,-1.35],[0,-.7+i*.05,-1.5],[.68,-.62+i*.057,-1.35]],.012,0x403b2c,.88);
    const stem=new THREE.Mesh(new THREE.CapsuleGeometry(.2,.68,10,24),mat('brainstem'));stem.position.set(0,-1.02,-.48);stem.rotation.z=.05;stem.userData.key='brainstem';brain.add(stem);pickables.push(stem);
  }
  function init(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(max-width: 640px)').matches?1.25:1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(31,1,.1,30);camera.position.set(7.6,.3,2.15);controls=new OrbitControls(camera,canvas);controls.enableDamping=!matchMedia('(prefers-reduced-motion: reduce)').matches;controls.dampingFactor=.07;controls.enablePan=false;controls.minDistance=5;controls.maxDistance=12;controls.target.set(0,0,-.15);scene.add(new THREE.HemisphereLight(0xcbe5e5,0x05090a,1.25));const key=new THREE.DirectionalLight(0xeafafa,2.25);key.position.set(-4,6,5);scene.add(key);const rim=new THREE.DirectionalLight(0x5fb8c1,1.05);rim.position.set(5,1,-6);scene.add(rim);const gold=new THREE.PointLight(0xc4a66a,.55,12);gold.position.set(-3,-2,2);scene.add(gold);buildBrain();resize();bind();readSignal(latestLocalEntry());root.querySelector('.brain-atlas__loading').hidden=true;root.dataset.ready='true';animate();window.__HEALTH_BRAIN__={ready:true,select,reset,zoom,readSignal,get selected(){return selected},get level(){return level},get cameraDistance(){return camera.position.distanceTo(controls.target)}}}catch(error){console.error(error);root.dataset.ready='false';root.querySelector('.brain-atlas__loading').textContent='3D UNAVAILABLE · USE STRUCTURE LABELS';bindLabels()}}
  function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
  function hit(x,y){const r=canvas.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1),camera);return ray.intersectObjects(pickables,false)[0]?.object||null}
  function select(key){const p=BRAIN_PARTS[key];if(!p)return;selected=key;root.querySelector('.brain-atlas__number').textContent=String(Object.keys(BRAIN_PARTS).indexOf(key)+1).padStart(2,'0');root.querySelector('.brain-atlas__panel h3').textContent=p.name;root.querySelector('.brain-atlas__description').textContent=p.description;const dd=root.querySelectorAll('.brain-atlas__panel dd');dd[0].textContent=p.group.toUpperCase();dd[1].textContent=p.view.toUpperCase();root.querySelectorAll('[data-brain-part]').forEach(b=>{const on=b.dataset.brainPart===key;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))})}
  function clearSelection(){selected=null;root.querySelector('.brain-atlas__number').textContent='00';root.querySelector('.brain-atlas__panel h3').textContent='Select a structure';root.querySelector('.brain-atlas__description').textContent='Choose a label or touch the model.';root.querySelectorAll('.brain-atlas__panel dd').forEach(d=>d.textContent='—');root.querySelectorAll('[data-brain-part]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')})}
  function reset(){clearSelection();camera.position.set(7.6,.3,2.15);controls.target.set(0,0,-.15);controls.update();brain.rotation.set(-.06,.1,-.025)}
  function zoom(direction){const distance=THREE.MathUtils.clamp(camera.position.distanceTo(controls.target)+(direction==='in'?-1:1),5,12);camera.position.copy(controls.target).add(camera.position.clone().sub(controls.target).normalize().multiplyScalar(distance));controls.update()}
  function readSignal(entry){level=expressiveLevel(entry);const neutral=level==null;root.classList.toggle('has-signal',!neutral);root.style.setProperty('--brain-signal',neutral?'0':level.toFixed(3));root.querySelector('[data-brain-signal]').textContent=neutral?'NEUTRAL · NO CHECK-IN':`${Math.round(level*100)}% · SELF-REPORTED`;root.querySelector('.brain-atlas__meter i').style.width=`${neutral?0:Math.round(level*100)}%`;root.dispatchEvent(new CustomEvent(BRAIN_EVENT,{detail:{level,source:neutral?'neutral':'local-checkin'}}))}
  function bindLabels(){root.querySelectorAll('[data-brain-part]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.brainPart)))}
  function bind(){addEventListener('resize',resize);bindLabels();root.querySelector('[data-brain-reset]').addEventListener('click',reset);root.querySelectorAll('[data-brain-zoom]').forEach(b=>b.addEventListener('click',()=>zoom(b.dataset.brainZoom)));canvas.addEventListener('pointerdown',e=>pointer={x:e.clientX,y:e.clientY});canvas.addEventListener('pointermove',e=>{if(e.buttons)return;hovered=hit(e.clientX,e.clientY);tooltip.textContent=hovered?BRAIN_PARTS[hovered.userData.key].name.toUpperCase():'';tooltip.hidden=!hovered;if(hovered){const r=viewport.getBoundingClientRect();tooltip.style.left=`${e.clientX-r.left}px`;tooltip.style.top=`${e.clientY-r.top}px`}});canvas.addEventListener('pointerup',e=>{if(pointer&&Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)<8){const target=hit(e.clientX,e.clientY);if(target)select(target.userData.key);else clearSelection()}pointer=null});document.addEventListener('pointerdown',e=>{if(!root.contains(e.target))clearSelection()});document.addEventListener('keydown',e=>{if(e.key==='Escape')clearSelection()});document.addEventListener('health:checkin',e=>readSignal(e.detail));addEventListener('storage',e=>{if(e.key===BRAIN_STORAGE_KEY)readSignal(latestLocalEntry())})}
  function animate(){raf=requestAnimationFrame(animate);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,pulse=reduced?1:1+Math.sin(performance.now()*.0025)*.08,signal=level==null?0:.25+level*1.35;for(const mesh of pickables){const active=mesh.userData.key===selected,over=mesh===hovered;mesh.material.emissiveIntensity=(.055+signal*.16+(active?.24:over?.1:0))*pulse}controls.update();renderer.render(scene,camera)}
  init();
}
