export const STORAGE_KEY='novaire-health-energy-checkins-v1';
export const SCHEMA_VERSION=3;
export const dayKey=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
export function scoreAnswers(a={}){const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0)),movement=['done','planned','recovery'].includes(a.movement)?10:0,total=Math.min(clamp(a.sleep,0,12)/8,1)*10+clamp(a.energy,0,10)+clamp(a.focus,0,10)+(10-clamp(a.stress,0,10))+clamp(a.calm,0,10)+clamp(a.happiness,0,10)+movement;return Math.round(total/70*100)}
export function normalizeEntries(value){if(!Array.isArray(value))return[];return value.filter(e=>e&&/^\d{4}-\d{2}-\d{2}$/.test(e.date)&&Number.isFinite(Number(e.score))).map(e=>({...e,score:Math.min(100,Math.max(0,Math.round(Number(e.score)))),legacy:e.schemaVersion!==SCHEMA_VERSION}))}
export function entriesFor(entries,view,now=new Date()){const days={day:1,week:7,month:30}[view]||1,cutoff=new Date(now);cutoff.setHours(0,0,0,0);cutoff.setDate(cutoff.getDate()-(days-1));const today=dayKey(now);return normalizeEntries(entries).filter(e=>e.date<=today&&new Date(`${e.date}T00:00:00`)>=cutoff)}
(() => {
'use strict';
const M=typeof window==='undefined'?null:window.HealthCheckinModel, KEY=STORAGE_KEY, API='/api/health-checkins';
const section=typeof document==='undefined'?null:document.querySelector('.energy');if(!section||!M)return;
const q=s=>section.querySelector(s), qa=s=>[...section.querySelectorAll(s)];
const form=q('.energy-form'), dialog=q('.energy-dialog'), sliders=qa('input[type="range"]');
let entries=[], revision=null, unlocked=false, view='day', selected=M.bangkokDate(), calendarMonth=selected.slice(0,7), detailDate=null, authGeneration=0, requests=new Set(), loadedDate=null, dirty=false;
function localPayload(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]'), valid=M.validatedEntries(raw);return{raw:Array.isArray(raw)?raw:[],valid,rejected:(Array.isArray(raw)?raw.length:0)-valid.length}}catch{return{raw:[],valid:[],rejected:0}}}
entries=localPayload().valid;
function beginRequest(){const controller=new AbortController(), generation=authGeneration;requests.add(controller);return{controller,generation}}
function requestCurrent(ctx){return ctx.generation===authGeneration&&!ctx.controller.signal.aborted}
function endRequest(ctx){requests.delete(ctx.controller)}
function safeError(response,fallback){if(response.status===401)return'Session expired. Unlock the private record again.';if(response.status===409)return'Check-ins changed on another device. Reload and retry.';if(response.status===413)return'Check-in request is too large.';if(response.status===422||response.status===428)return'The check-in data was rejected. Review it and retry.';return fallback}
function state(score){if(score>=70)return'#48e0b1';if(score>=40)return'#ffc45d';return'#ff6b62'}
function renderBattery(value){const populated=value!==null&&Number.isFinite(Number(value));section.classList.toggle('energy-populated',populated);section.style.setProperty('--energy-state',populated?state(value):'#61738a');qa('.energy-segment').forEach((el,i)=>el.style.setProperty('--fill',`${populated?Math.max(0,Math.min(10,value-i*10))*10:0}%`))}
function fmtBounds(a){return view==='day'?a.start:view==='week'?`${a.start} — ${a.end}`:`${a.start.slice(0,7)} · ${a.days} days`}
function appendText(parent,tag,text,className){const el=document.createElement(tag);if(className)el.className=className;el.textContent=text;parent.append(el);return el}
function renderMetrics(){const wrap=q('.energy-metrics');wrap.replaceChildren();for(const m of M.metricSummaries(entries,selected,view)){const card=document.createElement('article');appendText(card,'h4',m.label);let value='Unknown';if(m.average!==undefined&&m.average!==null)value=`${m.average.toFixed(m.unit==='L'?1:1)}${m.unit}`;else if(m.count){value=Object.entries(m.counts).filter(([,n])=>n).map(([name,n])=>`${name} ${n}`).join(' · ')}appendText(card,'strong',value);appendText(card,'span',`${m.count} / ${m.days} days answered`);wrap.append(card)}}
function renderHistory(){
 const shown=M.validatedEntries(entries).filter(e=>e.date<=M.bangkokDate()).sort((a,b)=>b.date.localeCompare(a.date)), byDate=new Map(shown.map(e=>[e.date,e]));
 q('.energy-history-count').textContent=`${shown.length} entr${shown.length===1?'y':'ies'} · private record`;
 const [year,month]=calendarMonth.split('-').map(Number), first=new Date(Date.UTC(year,month-1,1)), days=new Date(Date.UTC(year,month,0)).getUTCDate(), offset=(first.getUTCDay()+6)%7;
 q('.energy-calendar-label').textContent=first.toLocaleDateString('en',{timeZone:'UTC',month:'long',year:'numeric'});
 q('.energy-calendar-next').disabled=calendarMonth>=M.bangkokDate().slice(0,7);
 const calendar=q('.energy-calendar');calendar.replaceChildren();
 for(let i=0;i<offset;i++){const blank=document.createElement('span');blank.className='energy-calendar-blank';calendar.append(blank)}
 for(let day=1;day<=days;day++){const date=`${calendarMonth}-${String(day).padStart(2,'0')}`,entry=byDate.get(date),button=document.createElement('button');button.type='button';button.dataset.date=date;button.textContent=String(day);button.disabled=!entry;button.setAttribute('aria-label',entry?`${date}, ${Math.round(entry.score)}% battery`:`${date}, no check-in`);if(entry){button.className='has-entry';button.style.setProperty('--day-state',state(entry.score));button.setAttribute('aria-selected',String(detailDate===date));button.onclick=()=>{detailDate=date;selected=date;render()}}calendar.append(button)}
 const detail=q('.energy-day-detail');detail.replaceChildren();const entry=byDate.get(detailDate);
 if(!entry){appendText(detail,'p',shown.length?'Select a saved date to see its details.':'No private entries loaded. Unlock the private record or add a check-in.')}else{appendText(detail,'time',entry.date);appendText(detail,'strong',`${Math.round(entry.score)}% battery`);const a=entry.answers||{},f=entry.foundations||{};appendText(detail,'p',`Energy ${a.energy}/10 · Focus ${a.focus}/10 · Stress ${a.stress}/10 · Calm ${a.calm}/10 · Happiness ${a.happiness}/10`);appendText(detail,'p',`Sleep ${Number.isFinite(f.sleepHours)?`${f.sleepHours}h`:'unknown'} · Alcohol ${Number.isFinite(f.alcoholCount)?f.alcoholCount:'unknown'} · Sleep quality ${Number.isFinite(f.sleepQuality)?`${f.sleepQuality}/10`:'unknown'}`);const edit=appendText(detail,'button','EDIT THIS DAY');edit.type='button';edit.onclick=()=>open(entry.date)}
 const c=M.consistency(shown),grid=q('.energy-consistency-grid');grid.replaceChildren();
 const card=(label,value,note)=>{const el=document.createElement('article');appendText(el,'span',label);appendText(el,'strong',value);appendText(el,'small',note);grid.append(el)};
 card('Higher-battery stretch',c.recorded?`${c.highBest} day${c.highBest===1?'':'s'}`:'Unknown','Consecutive recorded days at 70% or above.');
 card('Lower-battery stretch',c.recorded?`${c.lowBest} day${c.lowBest===1?'':'s'}`:'Unknown','Consecutive recorded days below 40%.');
 card('Sleep under 7h',c.sleep.answered?`${c.sleep.matched} of ${c.sleep.answered}`:'Unknown',`${c.sleep.answered} recorded sleep answer${c.sleep.answered===1?'':'s'}.`);
 card('Alcohol 3+',c.alcohol.answered?`${c.alcohol.matched} of ${c.alcohol.answered}`:'Unknown',`${c.alcohol.answered} recorded alcohol answer${c.alcohol.answered===1?'':'s'}.`);
}
function render(){
 section.classList.remove('energy-previewing');
 const a=M.aggregate(entries,selected,view), value=view==='day'?(a.recorded?a.sum:null):a.progress;
 renderBattery(value);q('.energy-period-label').textContent=fmtBounds(a);q('.energy-period-next').disabled=a.end>=M.bangkokDate();
 q('.energy-percent').textContent=value===null?'—':`${value.toFixed(view==='day'?0:1)}%`;q('.energy-label').textContent=value===null?'NO CHECK-IN DATA':'ACCUMULATED BATTERY';
 q('.energy-coverage').textContent=`${a.recorded} of ${a.days} day${a.days===1?'':'s'} recorded · ${a.days-a.recorded} unfilled`;
 q('.energy-average').textContent=a.average===null?'Recorded-day average: —':`Recorded-day average: ${a.average.toFixed(1)}%`;
 q('.energy-empty').hidden=a.recorded>0;renderMetrics();
 document.dispatchEvent(new CustomEvent('health:checkin',{detail:view==='day'?(entries.find(e=>e.date===selected)||null):null}));
 renderHistory();
}
function updateSlider(input){const n=Number(input.value),visual=input.name==='stress'?10-n:n;input.style.setProperty('--range-color',`hsl(${Math.round(visual*12)} 78% 54%)`);form.querySelector(`output[for="${input.id}"]`).value=`${n} / 10`}
function foundationInput(){const out={};for(const el of qa('.foundation-grid [name]'))if(el.value!=='')out[el.name]=el.type==='number'?Number(el.value):el.value;return out}
function draftEntry(){const answers=Object.fromEntries(sliders.map(x=>[x.name,Number(x.value)]));return{date:form.elements.date.value,score:M.subjectiveScore(answers),answers,foundations:foundationInput(),draft:true}}
function preview(){const entry=draftEntry(),score=entry.score,f=M.foundations(entry.foundations);renderBattery(score);section.classList.add('energy-previewing');q('.energy-percent').textContent=`${score}%`;q('.energy-label').textContent='UNSAVED PREVIEW';q('.energy-coverage').textContent=`Draft for ${entry.date}. Save to update day, week and month history.`;q('.energy-average').textContent='Not included in saved totals yet.';document.dispatchEvent(new CustomEvent('health:checkin',{detail:entry}));q('.energy-breakdown').textContent=`Battery ${score}% · Foundations ${f.percent===null?'unknown':`${f.percent}% (${f.earned.toFixed(1)} of ${f.possible.toFixed(1)} available points)`}`;q('.foundation-score').textContent=f.items.length?f.items.map(x=>`${x.label}: ${x.earned.toFixed(1)}/${x.possible}`).join(' · '):'No foundation metrics answered; grade remains unknown.'}
function requireUnlock(){preview();q('.energy-label').textContent='UNSAVED · UNLOCK REQUIRED';const feedback=q('.energy-feedback');feedback.replaceChildren();appendText(feedback,'span','Nothing was saved. ');const button=appendText(feedback,'button','UNLOCK PRIVATE RECORD');button.type='button';button.className='energy-unlock';button.onclick=()=>{dialog.close();const target=document.querySelector('#health-private-pin')||document.querySelector('.health-private');target?.scrollIntoView({behavior:'smooth',block:'center'});target?.focus?.({preventScroll:true})}}
function breakdown(){const entry=draftEntry(),f=M.foundations(entry.foundations);q('.energy-breakdown').textContent=`Battery ${entry.score}% · Foundations ${f.percent===null?'unknown':`${f.percent}% (${f.earned.toFixed(1)} of ${f.possible.toFixed(1)} available points)`}`;q('.foundation-score').textContent=f.items.length?f.items.map(x=>`${x.label}: ${x.earned.toFixed(1)}/${x.possible}`).join(' · '):'No foundation metrics answered; grade remains unknown.'}
function populate(date){const e=entries.find(x=>x.date===date);form.reset();form.elements.date.value=date;form.elements.date.max=M.bangkokDate();sliders.forEach(x=>{x.value=Number.isFinite(e?.answers?.[x.name])?e.answers[x.name]:5;updateSlider(x)});for(const[k,v]of Object.entries(e?.foundations||{}))if(form.elements[k])form.elements[k].value=v;if(!e){form.elements.proteinTarget.value=130;form.elements.fluidsTarget.value=3}loadedDate=date;dirty=false;breakdown();q('.energy-feedback').textContent=unlocked?(e?'Loaded existing record. Saving will ask before replacement.':'Blank check-in ready to save.'):'Unlock Private health record with your Signal PIN before saving.'}
function open(date=M.bangkokDate()){populate(date);if(!dialog.open)dialog.showModal()}
form.elements.date.addEventListener('change',event=>{const next=event.target.value;if(!M.parseDate(next)||next>M.bangkokDate()){event.target.value=loadedDate;return}if(dirty&&!confirm('Discard unsaved changes and load the selected date?')){event.target.value=loadedDate;return}populate(next)});
form.addEventListener('input',event=>{if(event.target!==form.elements.date){dirty=true;preview()}});
form.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing&&event.target.tagName!=='TEXTAREA'&&event.target.type!=='submit'){event.preventDefault();form.requestSubmit()}});
async function loadServer(){const ctx=beginRequest();try{const r=await fetch(API,{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'},signal:ctx.controller.signal});if(!requestCurrent(ctx))return;if(!r.ok)throw new Error(safeError(r,'Private check-ins unavailable.'));const p=await r.json();if(!requestCurrent(ctx))return;entries=M.validatedEntries(p.entries);revision=p.revision;unlocked=true;q('.energy-sync').textContent='Private cross-device check-ins unlocked.';render()}catch(e){if(e.name!=='AbortError'&&requestCurrent(ctx)){q('.energy-sync').textContent=e.message;unlocked=false}}finally{endRequest(ctx)}}
window.addEventListener('health:record-ready',loadServer);
window.addEventListener('health:record-cleared',()=>{authGeneration++;requests.forEach(c=>c.abort());requests.clear();entries=[];revision=null;unlocked=false;dirty=false;loadedDate=null;if(dialog.open)dialog.close();form.reset();q('.energy-feedback').textContent='';q('.energy-sync').textContent='Locked. In-memory private check-ins cleared.';render()});
form.addEventListener('submit',async ev=>{ev.preventDefault();if(!unlocked){requireUnlock();return}const answers=Object.fromEntries(sliders.map(x=>[x.name,Number(x.value)])),date=form.elements.date.value,existing=entries.some(x=>x.date===date);if(date!==loadedDate){q('.energy-feedback').textContent='Date changed unexpectedly. Reload that date before saving.';return}if(existing&&!confirm(`Replace the existing private check-in for ${date}?`))return;const entry={date,answers,foundations:foundationInput(),clientUpdatedAt:new Date().toISOString()},ctx=beginRequest();q('.energy-save').disabled=true;q('.energy-feedback').textContent='Saving…';try{const r=await fetch(API,{method:'PUT',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({revision,entry,confirmOverwrite:existing}),signal:ctx.controller.signal});if(!requestCurrent(ctx))return;if(!r.ok)throw new Error(safeError(r,'Save failed.'));const p=await r.json();if(!requestCurrent(ctx))return;entries=M.validatedEntries(p.entries);revision=p.revision;selected=date;dirty=false;render();q('.energy-feedback').textContent='Saved privately across devices.';setTimeout(()=>{if(requestCurrent(ctx)&&dialog.open)dialog.close()},600)}catch(e){if(e.name!=='AbortError'&&requestCurrent(ctx)){preview();q('.energy-label').textContent='UNSAVED · SAVE FAILED';q('.energy-feedback').textContent=`${e.message} Nothing was saved.`}}finally{endRequest(ctx);q('.energy-save').disabled=false}});
q('.energy-import').addEventListener('click',async()=>{if(!unlocked){q('.energy-sync').textContent='Unlock the private record before importing.';return}const legacy=localPayload();if(legacy.rejected){q('.energy-sync').textContent=`Import blocked: ${legacy.rejected} local entr${legacy.rejected===1?'y is':'ies are'} invalid. Nothing was uploaded.`;return}const scale5=legacy.valid.filter(e=>e.scaleMax===5||e.schemaVersion===1);if(scale5.length){q('.energy-sync').textContent=`Import blocked: ${scale5.length} scale-5 legacy entr${scale5.length===1?'y needs':'ies need'} explicit migration; values were not silently rescored.`;return}if(!legacy.valid.length){q('.energy-sync').textContent='No valid legacy local entries found.';return}if(!confirm(`Import ${legacy.valid.length} local entr${legacy.valid.length===1?'y':'ies'}? Existing server dates will not be overwritten.`))return;const ctx=beginRequest();try{const r=await fetch(API,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({revision,entries:legacy.valid}),signal:ctx.controller.signal});if(!requestCurrent(ctx))return;if(!r.ok)throw new Error(safeError(r,'Import failed.'));const p=await r.json();if(!requestCurrent(ctx))return;entries=M.validatedEntries(p.entries);revision=p.revision;q('.energy-sync').textContent=`Imported without overwriting. ${p.conflicts.length} existing date${p.conflicts.length===1?'':'s'} skipped. Local copy retained.`;render()}catch(e){if(e.name!=='AbortError'&&requestCurrent(ctx))q('.energy-sync').textContent=e.message}finally{endRequest(ctx)}});
q('.energy-export').addEventListener('click',()=>{if(!unlocked){q('.energy-sync').textContent='Unlock the private record before export.';return}const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),entries},null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`novaire-health-checkins-${M.bangkokDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)});
qa('[role="tab"]').forEach(t=>t.addEventListener('click',()=>{qa('[role="tab"]').forEach(x=>x.setAttribute('aria-selected',String(x===t)));view=t.dataset.view;render()}));
function shift(dir){const p=M.period(selected,view),d=new Date(`${dir<0?p.start:p.end}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+dir);selected=d.toISOString().slice(0,10);if(selected>M.bangkokDate())selected=M.bangkokDate();render()}
function shiftCalendar(dir){const d=new Date(`${calendarMonth}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+dir);calendarMonth=d.toISOString().slice(0,7);detailDate=null;renderHistory()}
q('.energy-calendar-prev').onclick=()=>shiftCalendar(-1);q('.energy-calendar-next').onclick=()=>shiftCalendar(1);q('.energy-period-prev').onclick=()=>shift(-1);q('.energy-period-next').onclick=()=>shift(1);q('.energy-checkin-open').onclick=()=>open();q('.energy-close').onclick=()=>{dialog.close();if(dirty)render()};dialog.addEventListener('close',()=>{if(dirty)render()});sliders.forEach(x=>{updateSlider(x);x.addEventListener('input',()=>updateSlider(x))});render();
})();
